### ISSUE TITLE
Flare on Android

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#1221]
Some of you guys have been working on Android support for Flare.

I don't have the time or interest to maintain an Android version separately. So I'm looking for help or volunteers.

* Google Play account

Flare needs an official Google Play account. One of you major contributors is welcome to set up an official Google Play account for this purpose.

* File Hosting

Android game downloads have a file size limit. If someone wants to distribute flare-game on Android (~150MB), the data files will have to be hosted on a web server.

I don't want the flarerpg.org web server to host any main downloads -- I don't have the bandwidth for it anyway. That's why most things on the site like videos (YouTube) and downloads (Sourceforge) are hosted elsewhere.

Whoever is maintaining the android port should be in charge of keeping those files up to date, on whatever server they end up hosting on.

**Comment by igorko** [comment]
We agreed to not install data files with apk. Solution will be to allow user download official and non-official mods manually and just store them in public game folder on Android device.
