### ISSUE TITLE
graphics jumping about with hardware renderer

### ISSUE THREAD

**Issue by sudoman** [clintbellanger/flare-engine#1239]
i'm using an old machine here. the image on the screen would briefly appear shifted from the normal view. sometimes parts of the window did this, sometimes the whole window seemed to do this. I'm using a intel core duo L2500 with an internal 945GM. overheating has been an issue in the past, but i quit the game as this was happening and saw that the cpu temperature was only at about 70 degrees celcius.

````
Using Render Device: SDLHardwareRenderDevice (hardware, SDL 2)
INFO: No joysticks were found.
INFO: ItemManager: No item sets were found.
ERROR: MapRenderer: Could not spawn all enemies in group at maps/cave1.txt (x=57,y=11,w=1,h=1), 1 missing (min=1 max=1)
ERROR: [/home/sudoman/src/3rd-party/games/flare/install/master/share/games/flare/mods/alpha_demo/npcs/captured_trader.txt:7] NPC: 'random_stock' is not a valid key.
ERROR: SDLHardwareRenderDevice: Couldn't load image: Texture dimensions are limited to 2048x2048
````

**Comment by sudoman** [comment]
sorry, i didn't realize i didn't follow up on this earlier. i recall that there was other evidence that that laptop was indeed overheating (probably while playing flare.) i think that the thermal sensor i was looking at was incorrectly selected. on similar but different hardware i haven't seen that problem while utilizing proper cooling methods.

**Comment by dorkster** [comment]
Has there been any recent signs of this bug?

**Comment by sudoman** [comment]
No sign of this bug.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
