### ISSUE TITLE
Swooping Creature base AI

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#127]
Migrated from clintbellanger/flare#267

Add swooping creatures as a base movement AI type.

Some basics:

Charge attack state where they continue moving while deploying a hazard
They can only change directions 45 degrees at a time, instead of turning completely around. Use dir_favor and speed variables to make them move in arcs.
This is mainly to implement "flying" creatures, but this base type can be used for ground-based creatures as well.

**Comment by dorkster** [comment]
Much of the feature described here is possible now with the following commits:

- c304dc1a0253fa280158d9ecb55933826334ab27
- 96fdd7bfd317213f8eec08aba08d366a229e95a9
- 27753f6404f33b4024ef681f89c877d2f45bea73

With these commits, we can create "charge" powers that make the caster+hazard move in a straight line. An example of such a power is the [Shield Bash](https://github.com/dorkster/flare-game/commit/21c1bd22e4a668b7b3737d1ea1132efed87e2f27) I added to the Empyrean mod.
