### ISSUE TITLE
Make sure all log messages begin from new line  

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1340]
Issue reproduced when using SDL v1

In Map.cpp line 329, logError message misses "\n" in the end. Also logError and logInfo do not append "\n" to the end of message. As a result, if we do not add "\n" manually, message is not logged from new line.

There are two ways of solving this

1. Make sure we do not miss "\n" anywhere and add it where it is missing

2. (Preferred) Add "\n" inside logError and logInfo implementations. This will require removing std::endl from FileParser::error() as internally it calls logError(), so there is no need to add std::endl twice. Also for consistency we will need to remove all manually added "\n" from all error/info messages

I didn't doublecheck this on SDL v2 but I guess issue is not present there and adding newline is internally handled by SDL_LogMessageV, which is used inlogError and logInfo.

**Comment by dorkster** [comment]
>(Preferred) Add "\n" inside logError and logInfo implementations. This will require removing std::endl from FileParser::error() as internally it calls logError(), so there is no need to add std::endl twice. Also for consistency we will need to remove all manually added "\n" from all error/info messages

I agree with this method.

**Comment by dorkster** [comment]
Fixed in https://github.com/clintbellanger/flare-engine/commit/2475c5c14bb1eb1a3923b75c7e85f1cbe4fc0fc5
