### ISSUE TITLE
Android: fast frames after minimizing/restoring game app and after screen lock/unlock

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1341]
Steps to reproduce:

1. Load the game
2. Do not pause game, lock screen (or minimize game app)
3. Wait a minute and unlock screen (restore app window)
4. As result you will get fast frames some time after game resuming

**Comment by dorkster** [comment]
I guess this could be solved by pausing the game when locking the screen/minimizing the game. Does SDL provide a way to detect these events?

**Comment by dorkster** [comment]
SDL 2 provides these event types ([see this wiki page](https://wiki.libsdl.org/SDL_EventType?highlight=%28\bCategoryEnum\b%29|%28SDLEnumTemplate%29)):
- SDL_APP_WILLENTERBACKGROUND
- SDL_APP_DIDENTERBACKGROUND
- SDL_APP_WILLENTERFOREGROUND
- SDL_APP_DIDENTERFOREGROUND

From what I can gather, these are triggered when minimizing apps on Android (as well as minimizing on desktop OS). We could use these to skip game logic and rendering when minimized.

**Comment by igorko** [comment]
Fixed with #1347
