### ISSUE TITLE
Save structure

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-engine#1348]
As of now, saves are stored in a single text file. This is fine for our current needs, but the future of Flare points towards the possibility of generated maps/items mixed with pre-fab content. We'll want to re-organize how save files are structured.

I'd rather not try to cram everything into a single text file, so save "files" should actually be a directory. I imagine something like this:

- empyrean_save01/
    - maps/
    - items.txt
    - hero.txt (this would be our current style of save)

**Comment by igorko** [comment]
Shouldn't this issue be opened in flare-engine-next? We do not have generated maps in v1 nor generated items

**Comment by dorkster** [comment]
It would be a bit of future-proofing.

Plus it would add some organization to save files. For example, we could group together save files by SAVE_PREFIX instead of dumping them all in a single directory:
```
empyrean/1/avatar.txt
empyrean/2/avatar.txt
empyrean/stash.txt
poly/1/avatar.txt
poly/stash.txt
flare0.19/1/avatar.txt
flare0.19/stash.txt
```
