### ISSUE TITLE
Map_Enemy class not used

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1349]
I guess this is leftover after moving to enemy groups only. If I am right, we should remove this class.

**Comment by dorkster** [comment]
No it is still used in EnemyManager, Map, MapRenderer, and PowerManager.

**Comment by igorko** [comment]
Hm, are you sure it is used? When reading map from file,  we do not store data in Map_Enemy objects

**Comment by dorkster** [comment]
The enemy groups that are loaded by the map are eventually changed into individual Map_Enemy objects by `MapRenderer::enemyGroupPlaceEnemy()` and pushed into the Map object's `enemies` list.

**Comment by igorko** [comment]
I see now, in MapRenderer we use this class when reading enemies from group. But maybe we do not need Map member called "enemies" @dorkster, can you check it?

**Comment by igorko** [comment]
I see
