### ISSUE TITLE
How do I run the engine with the default mod?

### ISSUE THREAD

**Issue by Pajamaman** [clintbellanger/flare-engine#1356]
After cloning the flare-engine repo, I followed [these instructions](https://github.com/clintbellanger/flare-engine/blob/master/INSTALL.engine) to build the engine from source:

    cmake .
    make

I did not `make install` because I didn't want to install it for all users.

When I launch the flare executable, the "Play Game" button is grayed out. If I go to Configuration > Mods, there are no available mods to enable. I've tried a number of things including:

1. Symlink ~/.local/share/flare/default/mods to ~/Code/flare-engine/mods
2. Copy ~/Code/flare-engine/mods/ to ~/.local/share/flare/default/mods/
3. Copy ~/Code/flare-engine/mods/ to ~/.local/share/flare/mods/
4. Copy ~/Code/flare-engine/mods/mods.txt to ~/.config/flare/mods.txt
5. Edit ~/Code/flare-engine/mods/mods.txt to contain the line "default"
5. Edit ~/.config/flare/mods.txt to contain the line "default"

I'm left scratching my head. How do I run this thing?

**Comment by henrik-m** [comment]
I guess you are missing actual game files, which you can get from https://github.com/clintbellanger/flare-game (you just need the contents of the mods-subfolder, more specifically "fantasycore" and "alpha-demo"). The default mod itself will just show you the menu.

**Comment by dorkster** [comment]
@henrik-m is correct. The default mod is not a game unto itself, but rather a means to enable already installed games. I'll add a mention of this to the INSTALL file to prevent future confusion.

**Comment by Pajamaman** [comment]
Yep, that was it.
