### ISSUE TITLE
Memory access violation in AStarContainer destructor causes game to crash

### ISSUE THREAD

**Issue by henrik-m** [clintbellanger/flare-engine#1358]
I've been able to reproduce the crash every time by doing the following:

* Have new_game_mod installed (https://github.com/igorko/flare-mod-noname/tree/master/new_game_mod)
* Load the following savegame: https://db.tt/3vW9JfK0
* Spawn lots of allied monsters with your powers, at least "Summon Ghost Ally", but you can also spawn Goblins and Wyverns (relevant powers are already on the hotbar)
* Roam the asylum and the desert with your host of allied creatures (your ghost ally will summon lots of undead, let them do the work). After a few minutes the game will crash with a memory access violation.  With debugger attached I get the following stacktrace:

>	flare-engine.exe!AStarContainer::~AStarContainer() Line 39	C++
 	flare-engine.exe!MapCollision::compute_path(FPoint start_pos, FPoint end_pos, std::vector<FPoint,std::allocator<FPoint&gt; &gt; & path, MOVEMENTTYPE movement_type, unsigned int limit) Line 480	C++
 	flare-engine.exe!BehaviorStandard::checkMove() Line 422	C++
 	flare-engine.exe!BehaviorStandard::logic() Line 57	C++
 	flare-engine.exe!Enemy::logic() Line 108	C++
 	flare-engine.exe!EnemyManager::logic() Line 340	C++
 	flare-engine.exe!GameStatePlay::logic() Line 849	C++
 	flare-engine.exe!GameSwitcher::logic() Line 115	C++
 	flare-engine.exe!mainLoop(bool debug_event) Line 161	C++
 	flare-engine.exe!SDL_main(int argc, char * * argv) Line 297	C++
 	flare-engine.exe!main(int argc, char * * argv) Line 140	C

I have tested this with the current head (e7712386f6d1205d29837e3bfa0780c1e62d48cc).

When I have a breakpoint with hitcount on the line "delete [] nodes" the crash occurs always before the hitcount reaches 1000 on my machine, mostly in the range of 300-800.

The crash does no longer occur when I revert commit 0a1857f7c0ed38e30b9ec94f6c03e204955039a0  (which was the last one to introduce changes to AStarContainer.cpp) but I have not been able to determine what is wrong with the new code.

**Comment by henrik-m** [comment]
Awesome work! Crash is not happening anymore, although I noticed that memory consumption has gone up quite a bit. I'm running a debug build so it's not optimized or anything and the attached debugger could be a factor, but running exactly the same setup taskmgr showed around 160M-180M before (fairly constant) and rose steadily now up to 315M (until it crashed again, for different reasons). Is this expected?

**Comment by dorkster** [comment]
That doesn't sound right. Maybe it was the switch to using a vector for the array of nodes? I'll do some testing while watching memory usage. I could revert the change to using a vector, since it wasn't essential to the fix.

**Comment by dorkster** [comment]
Hmm, I'm not noticing any major differences. Keep in mind that textures are the biggest memory hogs, so loading many *different* creatures will take up quite a bit of ram. Especially large creatures like the adult wyvern.

**Comment by henrik-m** [comment]
That could indeed be an explanation. Earlier I had only a small goblin and the Ghost Ally, which mostly summons other ghosts and shades. All of which were already present as creature types in the Asylum.

**Comment by stefanbeller** [comment]
You could try to verify this with 'valgrind --tool=massif' (and looking at the generated report file with massif-visualizer or similar)
