### ISSUE TITLE
Minions block spawn position, preventing saving

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-engine#1361]
As the title says, spawned minions will be placed on the same tile that the player is when entering a new map. Since the tile is blocked for the player at that point, the game doesn't get saved as it should.

**Comment by henrik-m** [comment]
So that is the reason. I was already wondering why I start back in the Asylum every time the game crashes.

**Comment by dorkster** [comment]
Here's a video showing that this works with more than enough allies: http://a.pomf.se/cmwoiu.webm

**Comment by henrik-m** [comment]
Still happens occasionally. See here:

![image](https://cloud.githubusercontent.com/assets/8522449/6276522/d3da2088-b887-11e4-9ec1-02b8413008ea.png)

The hero is located under left wing of lower wyvern, between two ghosts. Maybe because of the narrow passage or the large size of the wyvern?

**Comment by dorkster** [comment]
I noticed this as well. My patch didn't cover allies that were spawned/converted by other allies. I'll try to come up with something more robust.

**Comment by igorko** [comment]
Btw, maybe this is related.. I have noticed that if there is a lot of allies on spawn point, avatar can't move to another map(So changing map message doesn't appear). To allow changing map I need to go away, so allies go away from spawn point, and then go back fast to spawn point, before allies come after me. This workaround helps to move to another map.

**Comment by henrik-m** [comment]
I was always under the impression that the map change tiles were blocked by allies that occupied them after map change. After the latest fix it is not that much of a problem any more, because your allies all start on the same tile beside you and don't block the map change trigger.
Of course you still need to circumnavigate your allies when you enter a narrow passage:
![image](https://cloud.githubusercontent.com/assets/8522449/6287229/4cc519ca-b910-11e4-997f-2bb99a4f5a80.png)

But if this situation arises in a finished game I would call that a game design issue, not one of the engine...

**Comment by dorkster** [comment]
A possible solution might be to have allies stay behind the player when not in combat. We could determine where "behind" is from the player's facing direction.

**Comment by henrik-m** [comment]
And if the player changes direction all allies try to get behind him? Might work...

**Comment by henrik-m** [comment]
Hm, I'm not sure if this would ultimately be a better solution than the current one. It is quite easy to spread your allies in the right direction as it is. If they all try to scramble behind you it might become a problem on maps with narrow corridors.

**Comment by dorkster** [comment]
That's true. Either way, let's leave the behavior as-is for 1.0. Our official game won't be making heavy use of minions (the player will have at most 1, if any).

The no-name mod uses lots of open spaces, so maybe the size of map exits should reflect that.
