### ISSUE TITLE
Should we still support SDL 1.2?

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-engine#1362]
Originally, we had two platforms that have kept us tied to SDL 1.2:

- GCW-Zero. The toolchain for this device now includes SDL 2 as a non-experimental library. So SDL 1.2 is not needed for this anymore.
- Amiga OS 4. Support for Amiga was dropped by the SDL team when moving to version 2. The last port of Flare to Amiga was v0.17 as seen [here](http://os4depot.net/index.php?function=showfile&file=game/roleplaying/flare.lha). From what I can gather there, performance wasn't very good to being with, though a lot has changed since the 0.17 days. Is it worth clinging to SDL 1.2 for this unmaintained port? I'd say no.

In my eyes, it's more a matter of **when** we drop SDL 1.2 than it is **if**. I would like to drop it before we release 1.0, since we could benefit from SDL 2's ability to scale graphics so that assets are about the same size regardless of the player's resolution.

Take these two user complaints for example:

- "The graphics are too small!!!"
- "I can't run this on my Amiga!!!"

I see us getting more of the 1st than the 2nd. :smile:

**Comment by pennomi** [comment]
I'd agree with dropping SDL 1.2 for Flare 1.0. No sense in looking backwards.

**Comment by clintbellanger** [comment]
I wouldn't mind dropping 1.2 support.

**Comment by igorko** [comment]
Hm, if I remember clearly, @clintbellanger was the one, who was against moving to SDL2, but it was long time ago, when SDL2 was in unstable shape. As for me, no opinion yet...

**Comment by Bertram25** [comment]
AFAIR, @clintbellanger was against moving as he said, sdl2 was using bits of proprietary code.
I don't know whether it is still true.
@clintbellanger why this change of mind? (Even if I do think moving on is a good thing ;])

**Comment by clintbellanger** [comment]
SDL2 wasn't stable or widely supported when we were making these decisions a long time ago. Should be much improved by now.

**Comment by igorko** [comment]
Does it really matter if we support SDL1 or no? It's just some small part of code that differs, and I do not see any problem in saving it as is.

**Comment by dorkster** [comment]
@igorko The reason is that I want to have runtime scaling of graphics (I did this in [my Ludum Dare game](http://dorkster.itch.io/nomans-dungeon)), which is only viable when we have GPU acceleration like in SDL 2. The other option is to implement that, but just not support it for SDL 1.2, but that doesn't seem like a good idea.

**Comment by dorkster** [comment]
The Windows build can't move to SDL 2 until SDL 2.0.4 is out (https://github.com/clintbellanger/flare-engine/issues/1359).

Our schedule might work out so that SDL 2.0.4 comes out before our 1.0 release. In case it doesn't, would it make sense to package the development version of SDL 2.0.4 with the Windows build? That's probably a bad idea, but I just thought I'd throw it out there, since it sounds like it's already pretty stable (and better than 2.0.3 on Windows).

**Comment by igorko** [comment]
Here is a list of what we miss now when don't support SDL1.2. https://wiki.libsdl.org/Installation#Not_supported_or_abandoned ... Maybe this is valuable for someone.
