### ISSUE TITLE
Increase number of available sound channels?

### ISSUE THREAD

**Issue by henrik-m** [clintbellanger/flare-engine#1363]
Is there a reason for the number of allocated channels here? Or is this a more or less arbitrary number?

>	SoundManager::SoundManager() {
		Mix_AllocateChannels(50);
	}

If so, could we ramp it up and/or - even better - make it configurable via command line parameters? "No more channels available" - errors appear pretty regularly on the noname-mod maps.

I've tested 128 channels on my machine without issues. The sound channel errors only started appearing when the number of simultaneously battling mobs began to really lag the game, at which point I would see it as an "unsupported number of enemies".

**Comment by dorkster** [comment]
I measured with massif and saw that each channel opened amounts to 72 bytes of memory. So that's about 3.5 KiB with 50 channels. With 128 channels we'd be using only 9 KiB.

So yes, we can bump it up.

**Comment by dorkster** [comment]
Fixed in 6a49c847d4f9ebd989f5a97b8c0e7e0d2fa7ccc7
