### ISSUE TITLE
Corpses do not disappear on blocked tiles

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1367]
I'll try to explain this. Happens in Ancient Temple. When you kill Wyvern above void, it's corpse is placed in void. I guess corpse, that is placed on blocked tile, should be removed from the map instantly.

**Comment by dorkster** [comment]
At least in the case of flare-game, void tiles are represented by water or
bottomless pits. So I think it would make sense to have corpses disappear
if they land in those locations.
