### ISSUE TITLE
Translation collision. 

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1379]
We have Chest slot in inventory menu and have Chest as container in poly and concordia data mods.  This causes one Chest string in po files and it can't be translated correctly in other languge as this word has two different meanings. Other data mods have no problems because all chests have their own names (e.g. treasure chest). I propose to rename Chest slot to e.g Torso, because imho Chest as container is used more frequently.

**Comment by dorkster** [comment]
I think Torso is an acceptable renaming here.

**Comment by clintbellanger** [comment]
Agreed, torso works here.

**Comment by dorkster** [comment]
Looks like this string isn't in the engine, but rather defined in the fantasycore mod. I'll update flare-game accordingly.

**Comment by dorkster** [comment]
Fixed here: https://github.com/clintbellanger/flare-game/commit/7b663d21c32aec411768e5a035b2a03d026a30c0
