### ISSUE TITLE
Issues with parsing directories under WIndows XP

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1395]
Initially reported by [Rem](http://opengameart.org/users/rem), investigated by me.
Here are Rem's original screenshots
![what it created](https://cloud.githubusercontent.com/assets/1015344/7346119/ec7df7be-ece3-11e4-9b14-d5de8d42d7c8.JPG)
![flare error](https://cloud.githubusercontent.com/assets/1015344/7346120/f20b2e36-ece3-11e4-8580-22d811edd200.JPG)

For me it didn't crash, but also produced a lot of errors in console and created some directories.
![image](https://cloud.githubusercontent.com/assets/1015344/7346134/13538d90-ece4-11e4-961a-a6836598cbc1.png)
Full paths:
...\flarev1.0pre 220\Settings\Administrator\Application
...\flarev1.0pre 220\and
...\flarev1.0pre 220\Data\flare\config
...\flarev1.0pre 220\Data\flare\userdata\mods
...\flarev1.0pre 220\Data\flare\userdata\saves

Error log: https://gist.github.com/igorko/c9096ecb7f44f8384205

First I thought it was language related (there is French in original issue paths), but as you see it's not.

Btw, for Rem, all works fine on flare v0.19 (without errors and creating empty folders).

**Comment by igorko** [comment]
Hm, Now I'm not sure, if this issue was present in v0.19, because release build we deployed was writing log into file, not console, so errors could be just ignored.

Also changed settings from UI are not saved, should be related to directories parsing/config file editing.

**Comment by igorko** [comment]
So let's suggest that "C:\Documents and Settings\Administrator\Application Data\flare" doesn't exist.
Let's see what is happening.
Settings.cpp -> void setPaths() -> getenv("APPDATA") != NULL -> createDir(PATH_CONF) -> if (isDirectory(path)) -> perror("isDirectory"); !!!

So as we see, stat(const char * _Filename, struct stat * _Stat) returns -1, and our path is not recognized as directory. But it looks like a correct directory... @dorkster Ideas?

**Comment by dorkster** [comment]
Looks like we're failing to handle spaces when creating directories on Windows. I never noticed this because I had no spaces in my APPDATA path. When I added a space in to `userdata` to make it `user data`, I got the same type of errors as Rem did.

**Comment by igorko** [comment]
My previous post was confusing a little. Errors happen if "C:\Documents and Settings\Administrator\Application Data\flare" exists.


Changing "APP_DATA\\flare" path to "C:\\data" fixes issue, there no errors anymore. (Only at first start before directory was created).

**Comment by dorkster** [comment]
@igorko Do the errors persist with the commit I just pushed?

**Comment by igorko** [comment]
Nicely done! Tested on Windows XP and all works fine.
