### ISSUE TITLE
Holding up shield while Character menu is open causes game to lag

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1399]
This can be caused by the fact that holding up the shield updates some stats which are shown in character menu, but this is anyway an issue, maybe we can avoid lag somehow...

**Comment by dorkster** [comment]
I'm not noticing any lag when blocking with the character menu open. I ran with perf and didn't see any noticeable differences in CPU usage.

**Comment by igorko** [comment]
Russian locale lags too, and I'm trying on Android

**Comment by dorkster** [comment]
Yes, I'm getting the lag when testing with Ukrainian and Russian. So it seems to only happen with Cyrillic characters?

**Comment by dorkster** [comment]
It seems to be linked to `FontEngine::trimTextToWidth()`, since the lag disappears when I don't use this function in WidgetListBox. I'll keep digging.

**Comment by dorkster** [comment]
Looks like we've been here before: https://github.com/clintbellanger/flare/issues/215. `FontEngine::calc_width()` is the culprit, `TTF_SizeUTF8()` more specifically.

To be fair, the list box in the character menu is wide enough that we probably don't need to be trimming text to fit inside it. We could add an option for list boxes to disable text trimming.
