### ISSUE TITLE
Transformation issues

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1410]
This can be fully on data side, but posting it here because it's related to different games.

Poly:
![33](https://cloud.githubusercontent.com/assets/1015344/9192141/cdfbe88e-4010-11e5-8631-aaf9d81bba99.png)

Noname mod
![11](https://cloud.githubusercontent.com/assets/1015344/9192147/d501985e-4010-11e5-97d3-6ff352f795a0.png)
![22](https://cloud.githubusercontent.com/assets/1015344/9192146/d500bb28-4010-11e5-90ee-5ca32f5361ed.png)
Noname mod - transform used - werewolf 5. As you see we have power at hotkey 1, which does nothing and has no name

**Comment by dorkster** [comment]
Fixed with https://github.com/clintbellanger/flare-engine/commit/6153d0454c6c17cef0c9516c468e7b8c4d7adc5a and https://github.com/clintbellanger/flare-engine/commit/872d233830294218eda55bb4f76cf74ececc8eeb
