### ISSUE TITLE
Minimap pre-rendering is very slow on Android tablet

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-engine#1421]
Whenever the minimap is updated (map change, event mapmod), the game freezes for a sizable amount of time. As the title mentions, this only happens on my Android tablet. Using the hardware renderer on my desktop does not exhibit this behavior.

Commenting out SDL_RenderDrawPoint() in SDL_HardwareImage::drawPixel() seems to reduce most of the lag. Maybe we need to use a single call to SDL_RenderDrawPoint**s**() instead of multiple calls to the former.

**Comment by igorko** [comment]
Didn't note such issue on my Samsung Galaxy Tab 3

**Comment by dorkster** [comment]
My Alcatel A463bg doesn't have this issue. And even if it did, I don't think the work necessary to make this perform better is worth it. Closing.
