### ISSUE TITLE
Scripting System

### ISSUE THREAD

**Issue by AustinHaugerud** [clintbellanger/flare-engine#1426]
I've beeen doing some studying on scripting implementations in game engines, Lua being the primary language I've studied on how to embed. Some questions have to be asked though.

  1.) Do you think Flare would benefit noticeably from having a scripting system?

  2.) What kind of tasks would you want scripts to be able to accomplish?

  3.) In what parts of Flare do you think the scripting system would exist optimally?

  3.) What kind of negative effects do you foresee with a scripting system?

**Comment by igorko** [comment]
We already have 3 issues about scripting (besides this we have https://github.com/dorkster/flare-engine-next/issues/13 https://github.com/clintbellanger/flare-engine/issues/1228 ). First of all we shoul deside if we need it in flare v1.0, then close all issues except one. @clintbellanger , @dorkster , @pennomi

**Comment by clintbellanger** [comment]
I think flare-engine-next would be best for introducing scripting.

**Comment by dorkster** [comment]
I agree with Clint. Let's keep discussion of this on the flare-engine-next issue.
