### ISSUE TITLE
0.20 release announcement

### ISSUE THREAD

**Issue by akien-mga** [clintbellanger/flare-engine#1430]
Hi there,

I was just checking up on Flare to see if there was still upstream activity, and I'm pretty happy to see there is still a regular inflow of commits. And I was even more happy to see there has been a 0.20 release in August!

But someone it hasn't been announced on flarerpg.org, which still mentions 0.19 as the latest release. It would be nice to make a release announcement for 0.20 too to give some more visibility to Flare again.

**Comment by akien-mga** [comment]
Ping?

**Comment by dorkster** [comment]
Sorry for the late response. We had/have no intention of doing a formal release of 0.20.

The new Empyrean campaign isn't completed yet. Rather than just put out 0.20 with the unchanged alpha_demo, we want to provide the 1.0 engine alongside the finished Empyrean campaign as a complete package. This release would coincide with a revamp of our website, which all together will make something we are confident in showing people.

**Comment by akien-mga** [comment]
Thanks for the answer :) So I guess I shouldn't package the currently tagged 0.20 for my distro (Mageia) for the time being, but wait for 1.0?

**Comment by dorkster** [comment]
Correct, 1.0 will be the next version we encourage packagers to package.

**Comment by mquinson** [comment]
Would it be possible to have a little notice when v1.0 gets out? I cant wait to package it for Debian ;) BTW, I know that it will get released when ready, but could you maybe estimate the amount of work that remains before that release?

In any way, thanks for this great game, and keep up the good work !

**Comment by stefanbeller** [comment]
@mquinson 

It was usually packaged by Jan-Hendrik Peters and Manuel A. Fernandez Montecelo, maybe get in contact with them :)

**Comment by mquinson** [comment]
@stefanbeller yes, we work together for that. Thanks for taking care.

**Comment by akien-mga** [comment]
I guess this issue could be closed if there are still no plans to make intermediate releases before 1.0. Just wanted to drop a small "release early, release often", as there are *huge* changes in the git repos since 0.19 and it would be nice to have a pre-1.0 that could maybe spark some more interest in the project and bring new contributors (no promise there though, you know how free software projects work ;)).
