### ISSUE TITLE
Can't launch game on Windows

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-engine#1434]
I've gotten a few friends of mine to help out with play-testing (they all use Windows). Unfortunately, one of them is unable to launch the game. Here is the information I've gathered that may be of use:
- OS: Windows 7
- No window is displayed, and there is not output on the command line
- This person has their %APPDATA% and the game itself on a drive that is not C:\
- The flare.exe process continues to run indefinitely. Unable to "End Process"
- Avast antivirus is installed, but does not appear to be interfering
- I created a build with multiple lines of logging for each step for `init()` in main.cpp. Still no console output.
- Both Release and Debug builds fail
- There are actually 3 flare.exe processes running, despite running only once after a reboot.
- Running "flare.exe --help" yields no output

**Comment by igorko** [comment]
Can be related to #1396 . What is CPU on that machine?

**Comment by dorkster** [comment]
I don't know off the top of my head, but I do know that he just built his computer recently. I doubt it's a lack of instruction sets.

Also, the build I provided him is using SDL 2.0.4.

**Comment by igorko** [comment]
I will try by myself asap. Can you email me build you gave him? Also I will make my own build.

**Comment by dorkster** [comment]
User in question can run 1.0, so I'm closing this.
