### ISSUE TITLE
Android : avatar moving is broken

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1435]
Cant move when mb1 power is set and available(not disabled). Power is executed and hero is moved a little, but stops then. So cant move by holding finger on touchscreen. Should be caused by recent power system changes(I guess)

**Comment by dorkster** [comment]
I reverted the offending commits. (4705e310b7ca716668448f5c0c0a9f3c267117ff, 6ffce61b0d50084d9fe1a569e3e1e961cdefdfc8). The feature itself didn't work well in practice. When playing I kept accidentally queuing up additional attacks when I didn't want to.
