### ISSUE TITLE
flare accepts malformed command line options

### ISSUE THREAD

**Issue by sudoman** [clintbellanger/flare-engine#1438]
If I misspell `--renderer=sdl_hardware`, flare ignores the option and reverts to default behavior, which has the potential to cause confusion. I would prefer to be notified that I gave flare a bad command line option and for flare to then quit so that I may see my error.

**Comment by dorkster** [comment]
Flare doesn't require command line options to run, so I don't like the idea of having Flare quit when an invalid option is encountered. I think it's acceptable to print an error, and then simply ignore the option.

**Comment by sudoman** [comment]
sounds good to me : )
