### ISSUE TITLE
When enemy runs away and there is wall in front of him, he stucks

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1454]
Noticed with minotaurs in empyrean. This looks like cheating, when you kill enemy in such way. Enemies should search the way in other directions, when there is a walll in front of them.

**Comment by dorkster** [comment]
Well, enemies can still attack when they cornered. It's just that the minotaur necromancer has no attacks besides spawning/healing minions. So this is not really a bug, but rather a game design flaw.

I experimented with having fleeing enemies continue to move when they were cornered. This usually resulted in the enemy moving directly towards the player, making them easy to kill. In fact, I think the fleeing behavior in general is more annoying to fight against than difficult.

My main goal was to create a more defensive enemy. I think I've come up with a good alternative that meets that goal. We should give the minotaur a temporary force field that reflects damage/missiles and knocks back the player. The protection will give the minotaurs time to summon their minions, while also providing an indirect way to damage the player. To implement such a power, hazard powers will need a few additional flags, but nothing complicated.

I think having enemies flee should be reserved as a temporary debuff, such as a scroll that scares all nearby enemies. Essentially, fleeing should be treated as "stunned, but still able to move".

**Comment by igorko** [comment]
In case of minotaur, I don't see any defensive logic when enemy stands near the wall, and wall is in front of him. You will attack him from behind, so there is no defense. When he can't just flee to right or to left, if there is free space? It's not always "cornered" state, currently enemy can stuck just near straight wall.
