### ISSUE TITLE
Refactor Tiled object "type" field usage to better support Tiled features?

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-engine#1456]
In version 0.16 of Tiled, a neat feature was added with the [Object Types Editor](http://discourse.mapeditor.org/t/tiled-0-16-0-released/1206). It allows specifying a default list of custom properties for objects that have a matching "type" field. Unfortunately, using this feature is difficult with the way we have used the type field for events, enemies, and npcs:

- Events store the method of activation in type, such as `on_trigger` or `on_load`.
- Enemies store the string for the enemy category that will appear in that area, such as `dungeon` or `skeleton`
- NPCs store the path to the NPC file to load, such as `npcs/udana.txt`

I would propose moving all of these to custom properties, and then using the type values of `event`, `enemy`, and `npc`. That way, it would be trivial to create an object types XML file for Tiled to use for Flare maps.

Does making this change seem worthwhile? The engine change would be relatively trivial, but the data specification change would **break all existing mods**. A general purpose migration script would need to be written fix existing maps (both Tiled TMX and exported, so modders don't have to re-export). Marking this as pre-1.0 since it is a major change to the data specification.

**Comment by clintbellanger** [comment]
A few unordered thoughts:

- Is this change better to make in the Tiled-specific Flare map exporter instead?
- Is the change major enough to move it to flare-next?
- Because I've used "type" so inconsistently (engine keyword? mod keyword? file? path?) I'd like to see this refactor done in the name of clarity anyway.
- I've always wanted map objects that can start with a default list of settings. e.g. basic_type = treasure_chest. Things like a treasure chest take a long list of properties, and many of them are the same each time.

**Comment by dorkster** [comment]
>Is this change better to make in the Tiled-specific Flare map exporter instead?

The purpose of this change is primarily a quality-of-life improvement when working in Tiled. So it doesn't make sense to make any changes to the exporter plugin.

>Is the change major enough to move it to flare-next?

I don't think so. We'd add a few more Event_Component ids for the properties we want to move. The "type" property would actually be ignored engine-side and used solely within Tiled. Very simple code changes overall.

>I've always wanted map objects that can start with a default list of settings. e.g. basic_type = treasure_chest. Things like a treasure chest take a long list of properties, and many of them are the same each time.

If we make this change, we will definitely have an Object Type named `event`, which will have *every* possible variable for events shown. For ease of use, we could definitely create a separate `event_treasure` type which has only the most common properties for chests. It's a shame we can't automatically grab the Tiled object's X/Y position for default values of properties like `mapmod`.

**Comment by dorkster** [comment]
Okay, I've finished the refactoring. I'll sleep on it before pushing upstream to make sure I haven't forgotten something that might have broke. In the meantime, the changes can been seen here:

- [engine](https://github.com/clintbellanger/flare-engine/compare/master...dorkster:map_object_refactor?expand=1)
- [flare-game data](https://github.com/clintbellanger/flare-game/compare/master...dorkster:map_object_refactor?expand=1) (warning: big diff)
- [the python script used to update game data](https://gist.github.com/dorkster/21ff4511689822824d9c79ec48a6138b)

And here's what the end result looks like in Tiled. As you can see, map objects are now color-coded by their type value, and we display all possible properties for the appropriate object.

![2016-05-02_202455](https://cloud.githubusercontent.com/assets/913982/14971927/172eac3e-10a5-11e6-8b5e-11740745a4bd.png)

**Comment by clintbellanger** [comment]
Wow! That screenshot really sells the feature. Having a reminder of everything possible while making maps is going to be helpful in being creative.

**Comment by dorkster** [comment]
Additional thought: We can probably generate `objecttypes.xml` from our engine source documentation.

**Comment by dorkster** [comment]
Changes are upstream now. I've sent pull requests to the flare-mod-noname and polymorphable repos as well.
