### ISSUE TITLE
Red crosshair below attacks or projectiles

### ISSUE THREAD

**Issue by hansjoachim** [clintbellanger/flare-engine#1464]
Playing with the latest master of flare-engine, I see red crosshairs below attacks or projectiles. Happens with my character as well as enemies. Looks like some debugging information which is left on.

An example:
![crosshair](https://cloud.githubusercontent.com/assets/3002493/17462325/a901f1f2-5ca9-11e6-9108-eec03fb7e1d9.png)

Tested with latest master (4e586dea9867b3e236af621d156f109b59fa78f8) with latest master of flare-game. Assume this is added in by the engine, but if not, feel free to reassign to -game.

**Comment by dorkster** [comment]
Ah, these are only supposed to appear when the dev console is enabled (Interface tab in Configuration menu) and the dev hud is on (defaults to on, can be toggled from dev console). Should be fixed now with https://github.com/clintbellanger/flare-engine/commit/7359b105b2b0aa768b4c14e00c41a3547d6bd5e4

**Comment by hansjoachim** [comment]
I've verified they are gone now. Thanks :)

>these are only supposed to appear when the dev console is enabled 

I figured it might be something like that, so I was a bit confused when they showed up with dev mode disabled.
