### ISSUE TITLE
Segmentation fault when pressing Esc

### ISSUE THREAD

**Issue by hansjoachim** [clintbellanger/flare-engine#1465]
Steps to reproduce:
1. Start a new game.
2. Press Escape.

Expected: the small dialog asking whether I want to quit.
Actual: the game segfaults (Thread 1 "flare" received signal SIGSEGV, Segmentation fault. according to gdb)

Reproducible with 76aaa9aa48093bc7210a50dc1eee990534d3c280 (self-compiled on Ubuntu 16.04)

**Comment by dorkster** [comment]
I'm unable to reproduce this. Can you provide a backtrace from gdb?

**Comment by hansjoachim** [comment]
```
Thread 1 "flare" received signal SIGSEGV, Segmentation fault.
0x00000000005fdb72 in MenuManager::logic() ()
(gdb) bt
#0  0x00000000005fdb72 in MenuManager::logic() ()
#1  0x000000000058cb7e in GameStatePlay::logic() ()
#2  0x0000000000594f2e in GameSwitcher::logic() ()
#3  0x000000000067e42f in mainLoop() ()
#4  0x000000000067edbe in main ()
```
Don't know how much that helps. Is there a way to build it to include line numbers in the backtraces.

**Comment by dorkster** [comment]
Looks like it only occurred when developer mode was disabled. It should be fixed in 9a1d359.

**Comment by dorkster** [comment]
By the way, you can enable debugging symbols for by doing:

```
cmake . -DCMAKE_BUILD_TYPE=Debug
```

**Comment by hansjoachim** [comment]
Thanks. I can verify it works with the latest commit now :)
