### ISSUE TITLE
Small refactor idea for BehaviorStandart.cpp

### ISSUE THREAD

**Issue by DoKel** [clintbellanger/flare-engine#1468]
I was looking into engine code, and found following construction in /src/BehaviorStandart.cpp:

>//work out who the kill is attributed to
>		bool source_hero = false;
>		bool source_ally = false;
>		bool source_enemy = false;
>		for (unsigned i=0; i<e->stats.effects.effect_list.size(); i++) {
>			if (e->stats.effects.effect_list[i].type == EFFECT_DAMAGE) {
>				switch(e->stats.effects.effect_list[i].source_type) {
>					case(SOURCE_TYPE_ALLY):
>						source_ally = true;
>						break;
>					case(SOURCE_TYPE_ENEMY):
>						source_enemy = true;
>						break;
>					case(SOURCE_TYPE_HERO):
>						source_hero = true;
>						break;
>				}
>			}
>		}
>
>		int bleed_source_type = source_hero ? SOURCE_TYPE_HERO : (source_ally ? SOURCE_TYPE_ALLY : (source_enemy ? SOURCE_TYPE_ENEMY : SOURCE_TYPE_NEUTRAL));

Which can be easily converted to following:

>int bleed_source_type = SOURCE_TYPE_NEUTRAL; //for case, then if() in loop will always be false
>for(...){
>if(...){
>if(e->stats.effects.effect_list[i].source_type != SOURCE_TYPE_ALLY &&
> e->stats.effects.effect_list[i].source_type != SOURCE_TYPE_ENEMY &&
> e->stats.effects.effect_list[i].source_type != SOURCE_TYPE_HERO
> ){
>bleed_source_type = SOURCE_TYPE_NEUTRAL;
>}else{
>bleed_source_type = e->stats.effects.effect_list[i].source_type;
>}
>}}

Or even without that weird if() check, in case, if there are only 4 states (I wrote code for case, if there is more than 4 possile sources, but all what is neither not ally, hero nor enemy have to be recognised like "neutral", cuz previous code did same).

That way it will be simplier, and  it removes 3 unneeded variables.

**Comment by dorkster** [comment]
Thanks for pointing out this piece of code. There was also a bug in there that I fixed while simplifying the code.
