### ISSUE TITLE
Add more advanced setup for threat_range

### ISSUE THREAD

**Issue by DoKel** [clintbellanger/flare-engine#1470]
As I mentioned in flare-game issue about ranged enemies (https://github.com/clintbellanger/flare-game/issues/518), safe-range (the range, closer than which fleeng enemies can't (for some reason they can, lol, guess it's some kind of bug, according to behaviour-standart's comments) get to hero) and range-after-which-player-is-assumed-missed are both hardcoded as threat_range/2 and therat_range*2 respectively.

In my opinion it's totally wrong, because one value rules 3 (at least) behaviour aspects. The idea is to provide following syntax for stats:
`threat_range=X, Y, Z`

Where, X is threat_ranged value itself, Y is divider for safe-range and Z is multiplier for miss-range. If Y and Z are not provided, engine can assume, they are default (both ==2).

Why is it useful?
Now threat_range for skeletons-shooters is set to 17. That is os because I did not wnat them to come to player closer than 8 units. But that also means, that they will follow player, even if he is 34 units far away (it's really long range!). That also means, that, on some maps, player won't even see skeletons, and they will already start shooting at him.
Nice configuration would be 12 threat-range, 8 safe-range and 20 (as default was 8*2=16) miss-range. And there is no way to provide such stats now.

I can try to implement it by myself, if you will accept the idea, but, probably, I will need some advises about how to do that best (at least, which file except StatBlock and BehaviourStandart have to affected).

**Comment by dorkster** [comment]
I'm all for removing hard-coded stuff from the engine, so this sounds like a good idea. Instead of multipliers, I  would use absolute values, which I think would be easier to understand for modders. So to mimic the engine default for a threat_range of 8, it would look like:

```
threat_range=8,4,16
# which is the same as...
threat_range=8
```

**Comment by dorkster** [comment]
You should be able to modify all three values now. Here's the new description of the threat_range key:

**threat\_range** | `float, float, float : Normal, Close, Far` | The first value is the radius of the area this creature will be able to start chasing the hero. The next two values are optional. The second value is the radius at which this creature will start moving to a safe distance. The third value is the radius at which this creature will stop pursuing their target.

**Comment by DoKel** [comment]
And so can I do like `threat_range = 5, ,10`, i.e. without "close" range? If no, that would be be better to swap "far" and "close", because second parameter works only on fleeing enemies.
Maybe `threat_range_close` have to be `fleeing_range`? You commited too fast ._.

**Comment by dorkster** [comment]
Yes you can do `threat_range=5,,10` (no space) and the close range will be 5/2. Or you could explicitly input that as `threat_range=5,2.5,10`.

**Comment by dorkster** [comment]
P.S. Do you still think we should swap the close and far positions? It does seem like that would make more sense.

**Comment by DoKel** [comment]
I think we have to move `threat_range_close` to `flee(ing)_radius`. Because only case, where that stat is used is fleeing.
Maybe latter there will be other situations, when some definition of "close range" will be needed, but making one stat for too purposes is bad, because some time before threat_range were used for multiply purposes too, and here we are.

**Comment by dorkster** [comment]
That sounds fair. I'll separate it into two keys.

**Comment by DoKel** [comment]
I generated too many minor ideas for commits, and every time you work to implement them...  Next time I'll try to pull request  solution, not just start discussion)

**Comment by dorkster** [comment]
Sorry. It's just that I got spare time and programming's fun :)

**Comment by dorkster** [comment]
Okay, [this](https://github.com/clintbellanger/flare-engine/commit/e8049388036123e2773c0e0035062ac6e09cab1c) should be better:

**threat\_range** | `float, float : Engage distance, Stop distance` | The first value is the radius of the area this creature will be able to start chasing the hero. The second, optional, value is the radius at which this creature will stop pursuing their target and defaults to double the first value.

**flee\_range** | `float` | The radius at which this creature will start moving to a safe distance. Defaults to half of the threat\_range.
