### ISSUE TITLE
crash on right click with shield

### ISSUE THREAD

**Issue by libregametester** [clintbellanger/flare-engine#1476]
I'm not sure what exactly made it crash there, but I set up the shield block ability to the right mouse button, and the game crashed when I clicked right. It happened twice when I tried it, here are the console outputs :

[ftp://g01.rhizogen.es/ac/bugs/flare/output.txt](ftp://g01.rhizogen.es/ac/bugs/flare/output.txt)

[ftp://g01.rhizogen.es/ac/bugs/flare/output2.txt](ftp://g01.rhizogen.es/ac/bugs/flare/output2.txt)

**Comment by dorkster** [comment]
Thanks for reporting this. It should be fixed now with https://github.com/clintbellanger/flare-engine/commit/7b1e11c453ff75b07d0d63d13a25df465d5542c5.
