### ISSUE TITLE
flare mercilessly refuses to start after choosing the wrong mod

### ISSUE THREAD

**Issue by libregametester** [clintbellanger/flare-engine#1477]
I've tried to add polymorphable in the list of mods, but I forgot to remove "fantasycore" before applying the changes. The game exited with this trace:

> INFO: No joysticks were found.
> INFO: Using Render Device: SDLSoftwareRenderDevice (software, SDL 2)
> ERROR: ModManager: Tried to enable "fantasycore", but failed. Game does not match "".
> ERROR: [./mods/polymorphable/engine/combat.txt:2] Settings: 'max_resist_percent' is not a valid key.
> ERROR: FontEngine: Unable to determine default font!

And now I can't launch it anymore:

> $ ./flare
> ERROR: FontEngine: Unable to determine default font!

(Edit: actually it has nothing to do with forgetting to remove "fantasycore", the same error happens without it)

**Comment by dorkster** [comment]
Polymorphable is out of date at the moment. Specifically, the font setting syntax is broken, so the game fails to launch.

For now, I pushed a [patch](https://github.com/clintbellanger/flare-engine/commit/f675346f4f0829c082ba0bce7ccc513610cf8a0e) that will reset your mod configuration when fonts fail to load properly. After failing to launch, the next launch will start with only the default mod enabled.

**Comment by libregametester** [comment]
Would it be relevant to have an option --enabled-mods=mod1[,mod2,mod3..] so you can choose which mod you're using before starting the game ?

**Comment by dorkster** [comment]
That sounds like a good idea. We could even use that to create launchers (Windows shortcuts, Linux .desktop files) for multiple games with a single engine installation.

**Comment by dorkster** [comment]
We now have a command line option, `--mods`, that behaves like you described: https://github.com/clintbellanger/flare-engine/commit/4dc02b768f749ee959896d00f57176a5a6809a77
