### ISSUE TITLE
[request] Door Settings Mod

### ISSUE THREAD

**Issue by scsijon** [clintbellanger/flare-engine#1481]
ENHANCEMENT REQUEST

I'm wondering if you could add to your Door settings a mod that limits the 'aviator' pass through ability.

ie, you can pass through the 'doorway' to another area providing your aviator is between Level X and Y.

So that if your aviator is a level 7 it can pass through a doorway that is set with a minimum of 5 and maximum of 10, but can't if your aviator is either a level 4 (area too hard) or 8 (area too easy)

**Comment by dorkster** [comment]
I believe what you're asking for is already possible in the engine. Although it would take some extra map events to display messages/play sounds when the player can't proceed. Here's how your example would be implemented:

```
# requirements for the door are met
[event]
intermap=maps/test.txt
requires_level=5
requires_not_level=11

# level too low
[event]
msg=The door is locked by a mysterious force.
requires_not_level=5

# level too high
[event]
msg=The door is locked by a mysterious force.
requires_level=11
