### ISSUE TITLE
[request] Random Doorways 

### ISSUE THREAD

**Issue by scsijon** [clintbellanger/flare-engine#1482]
ENHANCEMENT REQUEST

Could the 'doors' be set with Random ability settings?

ie, each time you pass through it it takes you somewhere different, either 

(1) coming out anywhere else in your game ,
 or 
(2) depending in your aviators Level to different areas.

**Comment by dorkster** [comment]
This could be useful for creating "endless" dungeons that grab from a pool of maps. Would be a nice substitute for not having full procedural map generation.

**Comment by clintbellanger** [comment]
Good idea. I've had this same thought before too. Some kind of teleport option that chooses from a list of maps. My thought was it could be mildly useful to do hand-crafted "endless" dungeons.

Another option, maybe more useful, is to allow 3rd party tools to generate large batches of random maps.

Random map generation is tightly linked to each tileset's rules. Given that the engine is very content neutral, it may make more sense to keep random map generation as a separate tool.

**Comment by scsijon** [comment]
On 03/11/2017 11:20 AM, Clint Bellanger wrote:
> Good idea. I've had this same thought before too. Some kind of teleport option that chooses from a list of maps. My thought was it could be mildly useful to do hand-crafted "endless" dungeons.
>
> Another option, maybe more useful, is to allow 3rd party tools to generate large batches of random maps.
>
> Random map generation is tightly linked to each tileset's rules. Given that the engine is very content neutral, it may make more sense to keep random map generation as a separate tool.
>
No I wasn't thinking if random maps, but that's an idea, just some user 
created areas and ones with oneway doorways (such as suddenly coming out 
of a wall or bookcase), I take it that's already available.
