### ISSUE TITLE
[Urgent] Ammendment to readme Doccument for Flare-engine 0.20 and above

### ISSUE THREAD

**Issue by scsijon** [clintbellanger/flare-engine#1483]
Could someone please add the comment in the readme.md that you now need SDL2 with the 'new' engine. I spent a few days trying to work out why it wouldn't build until I tracked it down.

0.19 only wanted the commonly used SDL1.2 and a lot of linux's havent fully implemented and packaged SDL2 anyway.

VERY frustrating for a new user!

**Comment by dorkster** [comment]
I've added a note to the Building from Source section of the README: https://github.com/clintbellanger/flare-engine/commit/59933051cb4f4109504c26dcf09364370d47f60f

Does that look okay?

**Comment by scsijon** [comment]
On 03/11/2017 11:20 AM, Justin Jacobs wrote:
> I've added a note to the Building from Source section of the README: https://github.com/clintbellanger/flare-engine/commit/59933051cb4f4109504c26dcf09364370d47f60f
>
> Does that look okay?
>
   Perfect, thank you, now to hope the linux's all implement SDL2 
completely as some only have one containing all and others have only 
part implemented it. But there is nothing we can do about that.

**Comment by dorkster** [comment]
>now to hope the linux's all implement SDL2

Arch has definitely spoiled me to the point where I forget some Linux distros have packages that are months, even years, behind upstream. That aside, I feel like SDL2 has good coverage at this point. And if it's good enough for Valve to ship in their run-time, it's good enough for us.
