### ISSUE TITLE
[request] relocation setting for flare-engine like in flare-game

### ISSUE THREAD

**Issue by scsijon** [clintbellanger/flare-engine#1486]
Can I ask for the addition of a configuration/build setting to relocate the engine away from /usr, like is in the flare-game.

In my case I like to use /opt/games as it has it's own partition for these 'play-toys'

**Comment by dorkster** [comment]
You can change the install prefix to something other than /usr with:

    cmake -DCMAKE_INSTALL_PREFIX=/opt

Use this in combination with `-DBINDIR` ,`-DDATADIR`, and `-DMANDIR` to control where Flare gets installed. [Here's](https://github.com/clintbellanger/flare-engine/blob/master/CMakeLists.txt#L35) what the defaults look like.

**Comment by scsijon** [comment]
thanks, maybe worth adding to the instructions somewhere, i'll close for now
