### ISSUE TITLE
Hit animation only shown once

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#1488]
During my testing it seems like the Hit animation (take damage) only plays the first time an enemy is hit.

This seems to only happen if cooldown_hit is not specified and left to default (that's the case in most enemy files). If I add the cooldown_hit explicitly in the enemy definition:

    cooldown_hit=266ms

It seems to work. The enemy will flinch every time they take damage.

To reproduce this, I suggest starting a new character, unequip your weapon, then punch the first enemy you see. If the bug exists, the enemy will flinch only the first successful hit. Can someone verify that this is happening on their end?

**Comment by dorkster** [comment]
Confirmed on my end. I'll try to fix this.

**Comment by dorkster** [comment]
When `cooldown_hit` isn't set, we use the duration of the hit animation of the enemy. We were [checking the wrong variable](https://github.com/clintbellanger/flare-engine/commit/2fa80fd622303451a4a1f28bbfef6c7a1f6ba3cf) where that happens, so it never got executed.
