### ISSUE TITLE
Make more main menu button positions configurable

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#1492]
GameStateTitle reads in the config file menus/gametitle.txt
There you can set the position of each button. E.g. I moved the Exit button up a little in Wandercall.

But these other main menu bottom buttons still have a default, not-configurable position:

GameStateNew has buttons 'Create' and 'Cancel'
GameStateLoad has the button 'Exit to Title'
GameStateCconfig has the buttons 'Ok', 'Defaults', 'Cancel'

**Comment by dorkster** [comment]
This was definitely on my TODO list, but I just never got around to it.

**Comment by clintbellanger** [comment]
This could be a good code assignment for a new contributor. The Title menu already has a working example, and all those other menus are already reading in other button configs.

**Comment by dorkster** [comment]
>This could be a good code assignment for a new contributor. The Title menu already has a working example, and all those other menus are already reading in other button configs.

True, but I was already half way in when I read that message. Figured I might as well finish it up. There always stuff to do and our contributors have been pretty adept when it comes to more complex stuff anyway.
