### ISSUE TITLE
Tooltip colors on primary stats

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#1495]
I get a black font when looking at the tooltips on Primary Stats in the character menu. Seems to be doing this for alpha_demo, empyrean_campaign, and wandercall_ch1. Can someone confirm?

The other tooltips in the scrolling stats area have a normal color. I'm guessing the Primary tooltip should use those same colors.

**Comment by dorkster** [comment]
I'm unable to reproduce this with all the mods you mentioned. The primary stats tooltips use the standard tooltip text color, which is `widget_normal`. You can try playing with the value of the same name in `engine/font_colors.txt` to see if it has any effect.

**Comment by clintbellanger** [comment]
I tested changing widget_normal. It affects the other widgets as expected but not the Primary Stats ones. Those are still black.

http://i.imgur.com/Vj81W6Y.png

(I made the tooltip background invisible so I can see the text.)

This is happening on two different computers for me, on all three mods.

**Comment by clintbellanger** [comment]
Weird wrinkle in this. The tooltips for the Name and Level are black too.

**Comment by dorkster** [comment]
Could you try the changes I made on [this branch](https://github.com/dorkster/flare-engine/tree/tooltip_test)?

**Comment by clintbellanger** [comment]
Confirmed this fixes the issue. Nice!
