### ISSUE TITLE
Poise or hyperarmor during power animations

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#1496]
I want to be able to set some powers so that the power use animation can't be interrupted by taking damage. As if the character gets 100% poise during the attack.

Specific examples I want to use this:

1. Once the ogre starts swinging a punch he can't be stopped. So the player should not just stand there and spam attacks.
2. Give some magic spells the ability to be cast uninterrupted. This could be good for spells meant to be used when surrounded like e.g. Quake from the alpha_demo, or a combat healing spell.
3. I want to make a Dash move that works as a dodge/roll. I want this to not be interrupted.

I think 3 can be done already though. If the dash power has its active frame near the beginning, it can just grant 100% avoidance for the same duration.

Can the others be done too? If not, is this worth adding?

**Comment by dorkster** [comment]
I don't think there's any to do those at the moment. So would a simple "prevent interrupt" flag be enough? Or should we have a way to buff the player 100% poise (or whatever) as soon as a power is cast?

**Comment by clintbellanger** [comment]
Hmmm yes, a simple interruptible flag might be ideal. That's pretty clear for modders.
