### ISSUE TITLE
Hazards that reflect on walls

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#1497]
I'm looking to allow moving hazards to bounce off walls. Right now if a moving hazard is inside a collision tile it gets a lifespan of 0 and is removed:
https://github.com/clintbellanger/flare-engine/blob/master/src/Hazard.cpp#L161

Maybe a new Power attribute for this:

    wall_reflect=true

The basic logic to add to Hazard.cpp::logic() inside the `if (collider->is_wall(pos.x, pos.y))` block:

- set the hit_wall=true either way
- if this hazard has wall_reflect, don't set lifespan=0. instead call a new hazard function for reflect()

This primitive reflect function takes in the current position x,y and speed x,y as currently calculated. That is, currently inside a collision tile. To find the new angle:

- if we move negative of speed.x are we out of collision? Then negate speed.x and move that much
- else if we move negative of speed.y are we out of collision? Then negate speed.y and move that much
- else negative speed.x and speed.y and move that much
- if this is a directional power, calculate and set the new direction

**Comment by clintbellanger** [comment]
I took a crack at this here:
https://github.com/clintbellanger/flare-engine/commit/f8f6ae65bf001b74421179f2e678e75a59681549

Seems to work. I tested in alpha_demo by making the Shock power (id=6) have this new trait:

    wall_reflect=true

The change was pretty small, but still keep an eye out for bugs with missiles.

**Comment by clintbellanger** [comment]
The aftermath of this change:
https://twitter.com/clintbellanger/status/866224856945373185

**Comment by SarcrofS** [comment]
@clintbellanger  is possible to make spells only bounce in ground? and is possible to make spells only be reflected by true wallls?

The stone in video will can be a little more amazing boucing in ground and being destroyed when hit a true "wall". A Lightning spell can be amazing only reflecting in walls and don't bounce in the ground too.

**Comment by clintbellanger** [comment]
@SarcrofS bouncing off the ground and bouncing off the walls are unrelated. The new flag is only for bouncing off walls. To bounce off the ground it's just using this animation: http://i.imgur.com/7NCih7k.gif

**Comment by dorkster** [comment]
@clintbellanger Spiky wheel-thing + pre-rendered 3D is giving me some serious Donkey Kong Country vibes.
