### ISSUE TITLE
Missiles only hit on animation active frame?

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#1498]
I may be missing a setting somewhere, but I think there's a bug related to animation refactoring on hazards.

Missile hazards are (usually) supposed to be Active every frame. That is, hazardous and colliding with entities every frame. But currently they are only hazardous on their active animation frame.

This may have not been noticed because many existing missiles have few animation frames?

This is a problem for long animations like Spikeball. The middle frame, the "active" frame, is the one where the ball hits the ground. I noticed after testing that I could run "underneath" the bouncing balls because they are only dangerous on one frame per bounce! I slowed the animation way down to test for sure.

The function Hazard::isDangerousNow() seems to not have an option for hazards with animations that are also active every frame.

Maybe a new Power and Hazard bool for marking a hazard that is dangerous every frame of its animation?

**Comment by dorkster** [comment]
Is there a reason you don't want to use `active_frame=all` for the spikeball animation? Hazard's are only supposed to do damage during their active frames. If you don't want to set all the frames as active, you can specify multiple frames for `active_frame`, e.g. `active_frame=4,5,6`.

**Comment by clintbellanger** [comment]
Ooh that's where the setting went. I'll try that and close this ticket.
