### ISSUE TITLE
Map file format design question

### ISSUE THREAD

**Issue by apocarteres** [clintbellanger/flare-engine#1505]
Hi folks, i recently started with Flare and lately come up with lots of questions. The most arguable questions i would like to discus are: 

- why Flare uses it's own map file format which mostly duplicates TMX? If it's due to decoupling with Tiled that's ok, but why Flare cares of Tiled extensions to read/write maps in Flare format then?  It could be much clearer if Flare had a tool which exports TMX as Flare map + tile atlas. I guess Tiled Flare extension is much more difficult to maintain rather than built-in Flare tool or third-party set of flare-tools.

- is Flare still alive? Does anyone know commercial games is being developed use Flare at the moment?

- are there guys here who are looking for a contribution in commercial project based on Flare?

I'm just sniffing around Flare and want to start developing something interesting to play :)

Have a good day to those who read this!

**Comment by dorkster** [comment]
>why Flare uses it's own map file format which mostly duplicates TMX?
I wasn't around when the decision to not use TMX was made, but here's my guesses as to why we don't use it:

1. An INI-style file parser is simple and something we could implement ourselves. XML is more complicated, so we'd either end up writing our own buggy parser or using an external library like libxml2. Neither is desirable.
2. There's an emphasis on modder's abilities to tinker with the game data as they please. INI files are more human-friendly than XML.

>is Flare still alive?

Yes, Flare is definitely alive! It *is* still a hobby project, so it will probably never match the development rate of a commercial project. That goes for open source / free software games in general.

>Does anyone know commercial games is being developed use Flare at the moment? Are there guys here who are looking for a contribution in commercial project based on Flare?

To my knowledge, there are no commercial games using Flare as an engine. But that doesn't mean you can't start one! As long as you adhere to the licenses of the engine (GPL) and the art content (mostly CC-BY, CC-BY-SA, and CC0), there's nothing stopping you from creating a commercial game with either component.

**Comment by apocarteres** [comment]
@dorkster thanks for reply. Yeah i got an idea of INI files and agree that they are smoother than other formats and don't require external dependencies, however i'm abit concerned with such things like a custom property for "tilesetdef" inside the TMX map, so it looks like a design issue to me, cause "tilesetdef" supposed to be derived from set of tiles described inside the TMX. So that's why i mentioned that it's either should be a) Flare uses TMX directly b) Flare keeps using it's own format but involved some tool or build-in function to make conversion aka TMX -> INI

**Comment by clintbellanger** [comment]
Tiled started in '08 and Flare's earliest work was in  '09. I had made the first several maps in a plain text editor before hearing about and starting to use Tiled. A format that is easily hand-edited was the only real priority.

**Comment by dorkster** [comment]
@apocarteres I forgot to mention that I had made a tool that creates the tilesetdef file when given a TMX map: https://github.com/dorkster/tilesetdef-generator. I haven't tested it in a while, so your mileage may vary. As far as I know, Clint created the tilesetdefs for the current Flare tilesets by hand, as they're slightly packed.

**Comment by apocarteres** [comment]
@dorkster thanks. will take a look
