### ISSUE TITLE
Is possible do use SVG instead PNG for images to create the game?

### ISSUE THREAD

**Issue by SarcrofS** [clintbellanger/flare-engine#1506]
Is possible do use SVG instead PNG for images to create the game?

I think is a good thing since SVG can adapt very well to changes of resolution.

**Comment by igorko** [comment]
Should check if SDL can handle this.

**Comment by pennomi** [comment]
You can't currently use SVG in-game. SDL isn't really designed for use with vector graphics.

You could however export those SVGs to PNG and use them that way.

**Comment by dorkster** [comment]
Like @pennomi said, SDL is intended to be used with raster graphics. So even if we *did* support SVG graphics ourselves, we'd convert them at runtime to bitmaps, which is simply not worth the effort.

**Comment by SarcrofS** [comment]
Thanks guys! 👍
