### ISSUE TITLE
how to start(boot) the flare-engine itself ?

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1525]
I do not know how to start the flare engine itself. What kind of command line is required?
What I do not know is not the installation method but the starting method.

In the first place, I don't know that even whether should booting the engine needed to develop games with flare?

**Comment by dorkster** [comment]
I'm a bit confused. In your other posts, you've clearly displayed the you were able to compile and run the Flare engine in order to play the alpha demo.

Perhaps you mean running Flare without any mods. That does not require any special command lines. Just go to the Configuration menu and disable all the Active Mods on the Mods tab.

**Comment by sujiniku** [comment]
The thing I want to ask is whether Flair has a GUI tool for game development.

For example, in Japan, such as  "RPG Tokuru" etc,  there is a game development tool that allows people without program knowledge to develop games.


And for example (not only Japan), in the development of GUI application of VisualBasic, there is one method of reducing keyboard operation as much as possible and developing by mouse operation on the screen in a method like GUI. For example, there is one method that setting the button to the window with mouse dragging etc.
It is a development support environment using GUI tools.

The flare engine looks like runtime to me. Because, When the flare game is started, it is necessary to always start the flare engine.

**Comment by dorkster** [comment]
Thanks for clarifying. Flare is as you say, a runtime only.

For creating maps, we use an external GUI program, [Tiled](http://www.mapeditor.org). I've written a [tutorial](https://github.com/clintbellanger/flare-engine/wiki/Creating-a-Map-in-Tiled) for making Flare maps in Tiled.

All the other components of Flare game development are done with plain text files. These files are formatted similar to INI files, and are all documented [here](https://github.com/clintbellanger/flare-engine/wiki/Attribute-Reference).
