### ISSUE TITLE
"You receive" message at the place where there is no opponent person

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1545]
"You recieve" is displayed at the time of getting item at quest progress. But in empyrean_campaign, opponent may not exist.

For example,  in empyrean_campaign, the hero may "recieve" a gravebloom flower above the altar in a place where there is no one but himself/herself.

I think that the "recieve"  word are to use when get the the something from other person.

So I think that not only "You receive" but also the "You get" message is should be prepared.

**Comment by dorkster** [comment]
I would say "You receive" and "You get" are interchangeable in English under this context. Translating it as "You get" would be acceptable.
