### ISSUE TITLE
Toughts about updating Flare in Debian

### ISSUE THREAD

**Issue by manuelafm** [clintbellanger/flare-engine#1549]
Hi,

I am the maintainer of this package in Debian (and derivatives like Ubuntu), and I was thinking about updating the game, not immediately (this week) but within a timeframe of 2-3 months.

We're stuck with 0.19 because I read a while ago that 0.20 was better skipped in favour of an upcoming 1.0 or something like that, but that was a long time ago.

So what are your plans for that?  Should I package the current latest version (0.20), or is it too outdated?  Waiting for a nex stable release...?

Cheers.

**Comment by clintbellanger** [comment]
@dorkster may have thoughts on when the engine 1.0 should go out.

We try to release flare-game content along with the engine that shows off the new features. The content needs to be generally finished and polished. Maybe we can look at the current content and pick a stopping point for a 1.0 demo?

I'm working on some new HD assets but I haven't built real content around them yet. So it'll be a while before I have a full demo on the new art.

**Comment by dorkster** [comment]
I've gotten a lot of inquiries recently about Flare's next release. So at the risk of setting a timeline and then failing to follow it as I've done before, let's set a timeline.

To allow some breathing room, 3 months would be ideal. With the amount of Empyrean content left to create, I can set aside the time to complete it within 4-6 weeks. The next week or two will be a brief play testing and bug fixing period. After this, we'll do a string freeze, announce 1.0 RC, and let translators do their work for the remaining time. The Empyrean campaign has much more content than the alpha demo, so I hope this will be enough time for them.

So some time in late February / early March, 1.0 will be released. Linux packaging is pretty well taken care of, and I can handle getting a Windows build together if no one else can. The OS X version seems like it's a bit unclear at the moment. Clint had previously provided that build, but it apparently has issues(?) on newer Macs.

For the 1.0 release, maybe it would be a good time to switch to the new site design I was working on. Clint, let me know if you'd like to get this done.

One final note: During the 4-6 week period, I will be in "do not disturb" mode. So any feature requests or things not pertaining to the Empyrean campaign will likely be ignored.

**Comment by clintbellanger** [comment]
This sounds good. I'll pick a weekend in Feb to do server updates and set up a test space for the new Flare Engine site. Then we can swap over to it once it's ready.

I can help with art assets that the campaign could use to finish things off. We can split that into another thread.

**Comment by manuelafm** [comment]
OK, sounds great.  I will hold it off until released then :-)

Looking forward to play, I haven't done it for a long time.

Thanks!

**Comment by sujiniku** [comment]
Releasing 1.0 means that the alpha release will end, is not it?
In case, we need change the name of "alpha_demo" mods to another name.

Otherwise (i.e. as long as keeping "alpha_demo" name), the user misunderstood that "this mods are not updated" and the user is confused.

**Comment by sujiniku** [comment]
Is Beta skipped?
There is not release for about two years from the previous version (v0.20). So I think that it is safer to do Beta test before RC.

**Comment by dorkster** [comment]
@sujiniku We've effectively been in a beta period for the past few years, despite the name of the alpha_demo mod. These days, the terms "alpha" and "beta" are generally not well defined. Some developers will release their "1.0" and continue to call it beta. In our case, I'm fine with skipping the "beta" label and going straight to RC. "RC" is just shorthand for "Release Candidate", which I think accurately describes the state our game will be in shortly before moving to 1.0.

**Comment by dorkster** [comment]
@manuelafm Just poking you to remind you that 1.0 has been released. So feel free to package :)

**Comment by manuelafm** [comment]
Thanks @dorkster .  I just had a huge spike of work and life stuff through over me since the beginning of the month, so unfortunately I cannot attend this at least until April.

Some people have shown interest though, I might pass on the token, or mentor or collaborate with them :)

**Comment by dorkster** [comment]
No worries. Just wanted to make sure you didn't miss it.

**Comment by manuelafm** [comment]
I have been working a bit on this, I have 1.06 almost ready to release for Debian unstable, and to then be present in the next stable release.

However, I faced several problems, the most important of which was buttons of the first screen not reacting (Play Game, Configuration, Exit, etc).  After thinking that it was a problem with touchpad, mice etc, I used --debug-events and everything seemed fine, and as last resort I moved the old config (from 0.19) away.  It then worked.

Is there any provision to adapt old configuration to new one, like for example invoking the binary with a special argument, or even converting names of variables in the files or something?

I understand that this is difficult etc, but just wondering and trying to preserve the game for those users who have games in the past.  Not sure how likely it is that they want to preserve previous sessions, but if possible it's better to have, specially from now on (version 1.0 and all that).

If not possible, I suggest to at least detect that there's old config and couldn't be loaded, and show a dialog that the game cannot continue until files are removed and and quit?

**Comment by dorkster** [comment]
We had some code that translated 0.19 keybindings into the 1.0 format, but it was a bit of a hack. As a better solution, I think we should add the engine version to the saved keybindings and check against it. If the engine version in the file is older than a set minimum engine version (or doesn't exist at all), we can load the default keybindings and display a message.

We recently introduced a way to load keybindings from mods which uses a more human-friendly syntax. Now would be a good time to make the saved keybindings use this syntax as well.

**Comment by manuelafm** [comment]
@dorkster Ah, that's an excellent solution :-)

**Comment by manuelafm** [comment]
@dorkster @clintbellanger and all other contributors: as part of testing the new release, I launched what I thought that it would be a under-5-minute game, and I ended up engaging and playing for days, disregarding other pending tasks, and I finished it minutes ago.  What you got here is quite an amazing and fun game.

I am not an avid gamer these days, but the only complex FOSS game built from the ground up that I remember grabbing my attention in a similar way was Wesnoth, many years ago.

So, lacking a better communication channel for doing so, here's are my congratulations for what you've achieved :-)

And, on the matter of the release, I suppose that I should wait for 1.07, specially if it contains the fixes for the settings and lack of response in the GUI with the old config files.

**Comment by manuelafm** [comment]
@dorkster @clintbellanger and others: So I released 1.07 in Debian unstable, and already entered "testing" (which means that in principle this will be the version for the next stable release, if not a newer one).

https://packages.qa.debian.org/f/flare-engine.html
https://packages.qa.debian.org/f/flare-game.html

Should we close this issue?

**Comment by dorkster** [comment]
@manuelafm Thanks!
