### ISSUE TITLE
post_power can not be zero

### ISSUE THREAD

**Issue by TaiVuong** [clintbellanger/flare-engine#1551]
https://github.com/clintbellanger/flare-engine/blob/7d30245c78d15a0a3632fd80bf33eaf038ff19ea/src/PowerManager.cpp#L944

```c++
if (activate(powers[power_index].post_power > 0 && percentChance(powers[power_index].post_power_chance)) {
activate(powers[power_index].post_power, src_stats, src_stats->pos);
}
```

**Comment by dorkster** [comment]
I don't see the issue here. Power IDs start at 1. We use 0 as a default value for post_power to indicate that it hasn't been set.
