### ISSUE TITLE
"?" is included when load at Japanese mode,

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1555]
At Japanese mode, when the class name("Grand Master" etc.) 's end is omitted as"..." on the load screen in the Japanese mode, the character "?" Is included.

![screenshot from 2018-01-17 19-23-00-a](https://user-images.githubusercontent.com/26195610/35038264-9dc34b74-fbbd-11e7-8f36-f2388a9d95e8.png)

Both alpha_demo and empyrean_campaign,this bug is occurred.
Perhaps, the length of Japanese one character is the length of English two letters, I think that it is related.

**Comment by dorkster** [comment]
This is a bug with our string shortening function not supporting multi-byte characters. I had [made a TODO](https://github.com/clintbellanger/flare-engine/blob/master/src/SDLFontEngine.cpp#L165) about this a while ago. I'll work on getting this working properly.

**Comment by dorkster** [comment]
Also to be clear, the "..." is an ellipsis, and is used to indicate that the text is longer than the area we're trying to display it in. So we chop off what can't be displayed and append the ellipsis.
