### ISSUE TITLE
"Loading ..." after "New Game"

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1567]
After "New Game" "Create" , It is confusing that "Loading ..." is displayed.
So, we should change the message of after New Game Creating to "Starting ..." etc.

**Comment by dorkster** [comment]
The concept of a "loading screen" is common for many video games, and is generally accepted terminology for loading game data from disk. We display the "Loading..." message whenever we change GameState, so the player will see it when clicking on "Play Game", before even encountering the "New Game" option.
