### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by bmorel** [clintbellanger/flare-engine#1568]
Hello.
I just pulled the last commit (8f35fbda92f4731cd5d3af4c5fdab46581e88bcb) and flare is **really** slow.
I have not investigated a lot, but I ran the game linked with google-perftools, to see if there might be something interesting (the generated pdf is  joined in this issue).
[prof.pdf](https://github.com/clintbellanger/flare-engine/files/1708267/prof.pdf)

Those are the results of the game compiled as Release (but linked with -lprofile after I noticed the performance problem).

From what I can see, SDL_LogCritical is called a lot and causes this performance problem (other high cost functions are called through it, and I must admit I'm impressed that something related to dbus seems to cause a lot of calls on a system where dbus is **not** installed, but it's not related to flare).

I would have attached a profile pdf for debug output, but it seems I have some issue with that, and can't produce any results at all.

**Comment by dorkster** [comment]
Was the performance okay before https://github.com/clintbellanger/flare-engine/commit/8f35fbda92f4731cd5d3af4c5fdab46581e88bcb? Also, are you running Flare with a language that's not English?

It would be helpful if you could post the contents of `~/.config/flare/flare_log.txt`.

**Comment by bmorel** [comment]
I do not remember the last revision that worked correctly, I think I checked something like 10 days ago?

I'm joining the log file.
[flare_log.txt](https://github.com/clintbellanger/flare-engine/files/1708529/flare_log.txt)

**Comment by dorkster** [comment]
The log only contains output from the last time you ran Flare. It gets overwritten every time the game is launched.

As far as I can tell this is not a bug on our end, as we're not the one calling `SDL_LogCritical()`. Possibly an oversight in SDL not accounting for systems without dbus, or a bug in dbus itself. I can't tell, because Arch's xorg-server package requires dbus to be installed.

**Comment by bmorel** [comment]
A simple test showed me that the problem is neither from flare nor from dbus not running: I have the perf problem only on de*v*uan testing, not on voidlinux (musl build). Sorry for noise.

**Comment by dorkster** [comment]
Good to know. Thanks for following up.
