### ISSUE TITLE
Reward pop-ups hides Guill's message

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1575]
In Averguard, When clearing some quests and talking to Guill, Reward's pop-ups overlap and Guill's message, so the player cannot be read the message.

As a countermeasure to prevent this situation, for example, when clicking a message, measures such as making Reward's pop-up hide are necessary.
Or we may change the location of the Reward's pop-up.

**Comment by dorkster** [comment]
>As a countermeasure to prevent this situation, for example, when clicking a message, measures such as making Reward's pop-up hide are necessary.

This is the current behavior. Reward messages are displayed in the hud log, which will display on top of other open menus. To dismiss the message and move it to being displayed behind the menus, click on it.
