### ISSUE TITLE
Cropped screen

### ISSUE THREAD

**Issue by SolMundus** [clintbellanger/flare-engine#1589]
withe modified element size in windows 10 (display setting/slider elements and texts size) screen size in flare are cropped 
thank for your hard work

**Comment by dorkster** [comment]
Interesting. Can you post a screenshot? Also, the contents of `%APPDATA%\flare\config\flare_log.txt` would be helpful if you could post them here.

**Comment by SolMundus** [comment]
![flarecropped](https://user-images.githubusercontent.com/36947149/36875268-5e5e3314-1e03-11e8-85cb-2bba065000ba.png)
![flarecropped2](https://user-images.githubusercontent.com/36947149/36875269-5eab589c-1e03-11e8-8ad8-f4bcbf751f2d.png)

strangly there is no log.txt in config

**Comment by dorkster** [comment]
Ah, looks like you're using version 0.19, which is vastly out of date. Try the Windows version linked on [this blog post](http://flarerpg.org/index.php/2018/02/24/flare-0-95-the-actual-1-0-release-candidate/). It uses SDL 2, which I think handles Windows dpi scaling better. I testing on Windows 7 with 125% scaling and had no issues.

**Comment by SolMundus** [comment]
ho sorry i can't even tell for what reason i have the outdated engine 
the progress are amazing !
 thank again for your work

**Comment by dorkster** [comment]
Thanks. Does that mean the screen is not cropped with the new engine?

**Comment by SolMundus** [comment]
yes everything looks perfect except that the screen seems to be "checking" when the character stop moving

**Comment by dorkster** [comment]
I'm sorry, but I don't understand what you mean by "checking". Can you elaborate?

**Comment by SolMundus** [comment]
no, i"m sorry i'm french so i have some trouble to write in english  what i mean is when my character stop moving in the empyrean game all the screen seems to slightly tremble (not a big deal)

**Comment by dorkster** [comment]
I understand now, thanks for explaining. What you describe is an artifact of our camera interpolation method that smoothly moves the camera towards the player. What we probably need is a threshold distance where the camera will just snap to the player if it's close enough, which would remove the "tremble" effect.

Anyway, I'm going to close this issue as the original question has been resolved.
