### ISSUE TITLE
It's possible to create wandering dead enimies (spiders)

### ISSUE THREAD

**Issue by vgaming** [clintbellanger/flare-engine#1592]
Steps to reproduce:

* increase offense/mental/physical maximum values in empyrean_campaign/engine/stats.txt
* go to area with spiders or skeleton archers (I was testing in Underworld)
* kill spider or skeleton from a large distance (try to get from as far as possible)

In about 1 of 10 cases, you will kill the unit in a very weird manner. It will still wander around. Upon howering it, you will see that it's "dead". It will never attack you. It still walks around with all visual animations. You cannot "kill" it further, bullets go through.

EDIT: removed "resolution" notes as further tests showed they are not relevant.

**Comment by vgaming** [comment]
UPD: it seems it's possible to create such a spider without excessive damage, too. Managed to create one right now. Antlion Burster level6. It does not walk around as spiders did on Underworld map, but it's visually alive, it breathes. Killed it **at close range** by either Ice Bolt or Shock by an adept 28 mental 9 defense mental-damage-min 77.

**Comment by vgaming** [comment]
@dorkster I've re-built and tried now -- it seems Antlion Burster still dies while remaining visually alive. Also, it seems that it's 100% reproducible  no matter what I do. The Burster does his kamikadze move and stays alive. Just moving near it forces it to attack and then make the bug appear.

Simplest repro steps: go to Stormrock Pass, enter Ruins, make the closest Burster attack you.

**Comment by vgaming** [comment]
UPD: the Burster stopped returning to base location though, so some change in logic indeed happened.

**Comment by dorkster** [comment]
Ah, I think the burster problem is separate. It likely has something to do with the recent moving of Enemy logic to the StatBlock class.

**Comment by dorkster** [comment]
Ok, it should be fixed now: https://github.com/clintbellanger/flare-engine/commit/d0452a9a7cc5af2c082d1d4d7922fa49a5d3e970

**Comment by vgaming** [comment]
Confirming the Burster spider is fixed, thanks!
