### ISSUE TITLE
Truncation issue in setup screen

### ISSUE THREAD

**Issue by gunchleoc** [clintbellanger/flare-engine#1594]
am having serious truncation issues in the game setup screen for the gd locale. Any chance of moving all those checkboxes to the right edge before the release?

![flare-truncation](https://user-images.githubusercontent.com/4095570/37114451-4b02bd80-2240-11e8-8924-75163ba4cf1c.PNG)

I know I'm late to the party, but after years of regularly checking the blog without any action on it, I started forgetting.

**Comment by dorkster** [comment]
Fixed with [this commit](https://github.com/clintbellanger/flare-engine/commit/8715e7bd6c9e560598dfb3ba70f40d9a3674b515). Here is what it looks like now:

![screenshot_2018-03-07_17-04-56](https://user-images.githubusercontent.com/913982/37120921-c3d530f6-2229-11e8-99fa-3e4c1fb03cbf.png)

**Comment by gunchleoc** [comment]
Excellent, thank you so much!

If you cuold also make the main menu buttons on the bottom a bit wider, it would look better. Maybe add another 3 em-spaces' width or so?

BTW Here's an interesting article on the subject: https://www.w3.org/International/articles/article-text-size

I have found that testing with Hungarian and Scottish Gaelic is usually pretty good, because one tends to be long where the other doesn't.

**Comment by dorkster** [comment]
Unfortunately, we use the same button for the keybindings list, which is already cramped.

Since we *can* use different fonts per-language, maybe we could try using a "condensed" font with narrower glyphs and a slightly smaller font size.
