### ISSUE TITLE
String truncation with "Hyperspace" in gd locale

### ISSUE THREAD

**Issue by gunchleoc** [clintbellanger/flare-engine#1605]
Any chance of giving me enough space to add the final "l"? Text is supposed to read "Ionad-siubhail".

![truncation ionad-siubhail](https://user-images.githubusercontent.com/4095570/37258702-77bf0334-2573-11e8-8633-8c210d139fb4.png)

Maybe give it the same code as dropped items, with dynamic width?

**Comment by dorkster** [comment]
Looks like the "l" simply wasn't added in the translation.

Fixed here: https://github.com/clintbellanger/flare-game/commit/4720884b610b47088f00e9985ef12124c526f186
