### ISSUE TITLE
Minion blocks path when trying to target enemies

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-engine#1608]
See 14:33 in this video: https://youtu.be/2OwlhodLdZI?t=14m33s

**Comment by sujiniku** [comment]
Let's let enable the hero pass through minion.
However, we should slow down speed while the hero are passing on minion. That way, it seems like a passing atmosphere is coming out and it's cool.

Also, even about enemies' party, let 's allow enemies in the back row to pass through enemies who cannot move in front line.  Even in classic turn-based RPG such as "wizardry", the sleeping enemies move to the back row.

To do that, enemies who cannot move should not just fix the position, they just need to be unable only to move spontaneously.
So, it is necessary for another enemy who can move to be able to push out locked enemy that cannot move.
