### ISSUE TITLE
Launching Flare from Windows installer results in error

### ISSUE THREAD

**Issue by gunchleoc** [clintbellanger/flare-engine#1609]
Running Flare straight from the Windows installer results in an error. It doesn't find the mods in AppData. Everything is fine if you run the exe normally though. One "mods" too many?

![launch_flare_from_installer](https://user-images.githubusercontent.com/4095570/37329875-2e7e7108-2697-11e8-954b-4b249ad49737.PNG)

I also installed to C:\Flare rather than the default install path, in case I need to mess with the files.

**Comment by dorkster** [comment]
Those are actually two separate paths

- `C:\Users\Beatrice\AppData\Roaming\flare\userdata\mods\`
- `mods\`

The second one is the one we're interested in, but it requires us to be in the correct working directory. The shortcuts we install set this properly, but I don't think the function we use to launch Flare from the installer does.
