### ISSUE TITLE
Game crashes after resize in game mode

### ISSUE THREAD

**Issue by crackedmind** [clintbellanger/flare-engine#1613]
Maybe related to #1612

Steps:
1) Resize window in game mode
2) Click close button

What we get:
- Game crashes

Expected:
- Game don't crash
- It's not happening without resize

Environment: 
- Windows 10

**Comment by dorkster** [comment]
This should be fixed with this commit: https://github.com/clintbellanger/flare-engine/commit/8333c532af54ea17032ce909a9c0c6a1236484b7. Please test.

**Comment by dorkster** [comment]
Oops, referenced the wrong issue in the commit. Fixed that.

**Comment by crackedmind** [comment]
Yep, it was fixed.
