### ISSUE TITLE
System to register mods without modifying flare-engine files

### ISSUE THREAD

**Issue by akien-mga** [clintbellanger/flare-engine#1614]
The current system to register mods is to modify flare-engine's [`mods/mods.txt`](https://github.com/clintbellanger/flare-engine/blob/master/mods/mods.txt) to list the new mods.

It works fine, but is problematic in the context of Linux packaging, if we expect (and I hope so) that new libre games will be made using FLARE, and packaged in Linux distros. (I just packaged flare-engine and flare-game 1.0 for my distro Mageia.)

The content installed by Linux packages is meant to be read-only, and a given package cannot modify files installed by another one. So if I were to package Polymorphable as a `polymorphable` package depending on `flare-engine`, I could not register it without modifying the main `flare-engine` package's `mods.txt`. Which defeats the purpose of mods, as I'd have to register all available mods in the main engine package for them to be usable.

It's already problematic in the current state as [`mods.txt`](https://github.com/clintbellanger/flare-engine/blob/master/mods/mods.txt) registers two mods which are actually shipped in another repo, [flare-game](https://github.com/clintbellanger/flare-game).

-----

**Proposed solution:** Make it possible to register mods without touching the files installed by `flare-engine`. It's easy to do by having a folder where mods can install a file with a unique name, and the engine will parse the contents of that folder to find registered mods.

So instead of a monolithic `mods/mods.txt`, we could have a collection of `txt` files from each mod, e.g.:
- `mods/empyrean_campaign.txt`
- `mods/fantasycore.txt`
- `mods/polymorphable.txt`
- `mods/thatothergreatgame.txt`
- `mods/thatweaponmod.txt`

Those files would be installed by each respective mod, so `flare-engine` would no longer need to hardcode the registering of `empyrean_campaign` and `fantasycore`, those two mods would do it themselves when installed.

The engine should go through all files in `DATADIR/mods/`, pick the ones with `txt` extension, and register the corresponding folders in `DATADIR/mods/` (if existing, otherwise issue a warning) as mods.

Two possible alternatives (if we're concerned about having non-mod `txt` files in the `mods/` folder):
- Write those in a subdirectory, e.g. `mods/enabled/`
- Write those with a hardcoded name directly in each mod's folder, e.g. `mods/empyrean_campaign/config.txt`

----

One missing feature from `mods.txt`, the priority order:

> Mods lower on the list will overwrite data in the entries higher on the list

It can be easily fixed by actually writing content in the `txt` files, and have a tag to define a priority order. Modders are then free to define a priority higher or lower than other mods depending on how they want their mod to modify the game. It could be a simple number, like a Z depth :)

Since each mod would now have their own files, it also paves the way for writing more metadata in those files, such as a mod pretty name (e.g. "Flare: Empyrean Campaign"), a description, a path to a picture/icon, etc. But that's out of the scope of this issue.

**Comment by dorkster** [comment]
>So if I were to package Polymorphable as a polymorphable package depending on flare-engine, I could not register it without modifying the main flare-engine package's mods.txt. Which defeats the purpose of mods, as I'd have to register all available mods in the main engine package for them to be usable.

The mods.txt provided in flare-engine is merely some suggested defaults we picked that can be safely ignored. If the mods in that list are not present, the game will still launch with the base "default" mod so that the user can access the Configuration menu to enable the mods that *are* installed.

Your idea is interesting, but it still seems like it falls apart when multiple games are installed. So let's say you have packages for flare-game and polymorphable. Both of them add their mods to the "default enabled" location. Flare would then try to enable all of them, which wouldn't work.

>Since each mod would now have their own files, it also paves the way for writing more metadata in those files, such as a mod pretty name (e.g. "Flare: Empyrean Campaign"), a description, a path to a picture/icon, etc. But that's out of the scope of this issue.

Mods already have metadata. It is located in at `$MOD/settings.txt`. The current available properties are listed [here](https://github.com/clintbellanger/flare-engine/wiki/Attribute-Reference#modmanager).

**Comment by akien-mga** [comment]
> The mods.txt provided in flare-engine is merely some suggested defaults we picked that can be safely ignored. If the mods in that list are not present, the game will still launch with the base "default" mod so that the user can access the Configuration menu to enable the mods that are installed.

Oh, I indeed misunderstood the purpose of `mods.txt` then, I thought it was what registered mods as available, not as enabled by default. If all mod folders are automatically registered as available, what I described above is basically implemented already so this suggestion is moot :)

At most `mods.txt` could maybe be renamed to `default_mods.txt` for clarity, but that's nit-picking.
