### ISSUE TITLE
The String"Reset Lock File" is protruding.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1615]
![multiple_start](https://user-images.githubusercontent.com/26195610/37408594-c2f56adc-27df-11e8-8686-7f81656b9856.png)

OS: Windows 7
Flare version: 1.0 (installed by "flare_install_v1.0.exe")

**Comment by dorkster** [comment]
I suppose this is an SDL bug in regards to not making that button big enough.

Of course, we could shorten our text to something like "Reset", and add some text to the body of the dialog explaining what that means.

**Comment by sujiniku** [comment]
In the first place, I don't know what happens by clicking "Reset Lock File" button.

Does it mean doing "Reset" the "Lock File"? Or does it means the "Reset Lock" the "File"? Or does it means doing "Reset" and "Lock" the "File"?
In above cases, what is the "Lock File"? What is the "Reset Lock"?

**Comment by dorkster** [comment]
Good point. Most users aren't going to know what the lock file refers to.

How would something like this be?:
![screenshot_2018-03-14_13-56-59](https://user-images.githubusercontent.com/913982/37421507-d8f329c8-278f-11e8-959e-953a6e7f1aef.png)

Also interesting that the order of the dialog buttons is reversed on Windows. Pretty sure that's intentional on SDL's part, though.

**Comment by sujiniku** [comment]
Sorry, I dont know what "instance" means.
I feel that "instance" is an IT-related technical term.
Therefore, even if it says "reset the instance", I don't know what is reset, and I don't know what happens after "reset".

**Comment by dorkster** [comment]
Okay, I dropped the term "instance" from the descriptions:

![screenshot_2018-03-14_14-21-25](https://user-images.githubusercontent.com/913982/37422964-009e91b2-2793-11e8-9444-84caa81c9187.png)

**Comment by sujiniku** [comment]
I actually started up on Windows and tried clicking these buttons sometimes.

I understood ..., although I don't start multiple starting indeed, but if Flare erroneously detected multiple starting ,
then if clicking this "Reset" button, then the lock will be reset.

So, after clicking "Reset", the player will be able to start flare.
if the player dont click "reset", at worst case, player cannot start flare.

I understand.
