### ISSUE TITLE
Powers tab should default to character type

### ISSUE THREAD

**Issue by tvleavitt** [clintbellanger/flare-engine#1621]
When I reload my Scout/Ranger savegame, the Powers screen defaults to the "Warrior" tab. Not thinking about what I was looking at, I wound up adding "Powers" from the Warrior tree rather than the Ranger one. Fortunately, these were passives and thus still useful, but the tab should really align to the character type by default.

**Comment by dorkster** [comment]
We could consider adding an attribute to the [character class definitions](https://github.com/clintbellanger/flare-engine/wiki/Attribute-Reference#settings-classes) that defines a default power menu tab to switch to whenever that menu is opened. This would be the most flexible while still supporting games that don't have a 1:1 correlation between classes and power menu tabs.
