### ISSUE TITLE
Broken Mouse / Keyboard event handling

### ISSUE THREAD

**Issue by un404known** [clintbellanger/flare-engine#1649]
I can't trigger this issue with a proper mouse but only with a touchpad:

1. Move Swing to a Hot Key
2. Press the Hot Key and keep it pressed
3. Try to move the cursor with your touchpad
4. The cursor is locked until you release your hot key.

**Comment by dorkster** [comment]
Some laptops have a setting where it will disable the touchpad if it detects the user is "typing" (i.e. pressing a key). Maybe that's what's happening here.
