### ISSUE TITLE
Non-living things can be “Dead”

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-engine#1656]
Sometimes, an enemy is not a living being but more like an object. But when you kill it, the word “Dead” appears at the health baw on the top of the screen. This word does make sense in this context.

I suggest the following: For enemies, make it somehow possible for the mod maker to specify the “death type”, this will determine the label when the enemy has been “killed”. There should be 2 default death types:

- Dead (default)
- Destroyed

Other types might be added later, but let's keep it simple for now. :-)

This affects the Empyrean Campaign. If you “kill” a cursed grave, it will be “Dead”. A more appropriate word would be “Destroyed”. See also: https://github.com/clintbellanger/flare-game/issues/757

**Comment by dorkster** [comment]
Fixed:

- 1f50d1a1cc6e27f76cba973a4056f61e5825139d
- https://github.com/clintbellanger/flare-game/commit/8441e1a179241c442da83ae0f2b4c1dd4bb4e7af
