### ISSUE TITLE
1 remaining points

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-engine#1661]
If you have 1 remaining point to spend on character stats, Flare shows “1 remaining points”.

Flare 1.06.

**Comment by dorkster** [comment]
I created new strings that take plurality into account. The sources on Transifex should be updated.

**Comment by Wuzzy2** [comment]
> I created new strings that take plurality into account.

Ummm ...
That's not how it's supposed to be done.

Please research how plural forms work *properly* in Gettext, thank you.

**Comment by dorkster** [comment]
I'm aware, but our GetText implementation does not have ngettext support at the moment. So this is this best I can do for now.
