### ISSUE TITLE
“Cut scene” usability problems

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-engine#1662]
It's a bit too easy to miss the intro texts or texts in “cut-scenes” (intro and end sequence in Empyrean Campaign). With “cut scene” I mean the sequences of images with some lore text.
This issue is partly related to engine, partly related to Empyrean Campaign.

There are several problems:
- If you don't do anything, the screen changes automatically. This is bad, the player might be a slow reader, look at the nice-looking image or be simply AFK
- There is no back button. If you misclick or wait, the text is gone forever
- It's not clear which is the final screen in a sequence. If you misclick or wait, the entire sequence is gone forever

Suggestions:
- Don't change screen automatically
- In an end sequence (like in Empyrean Campaign), add an optional special screen saying “The End” before rolling the credits :)
- On the final screen in a sequence, change the arrow button on the top right to a different button labelled “Close”/“Finish”/“Start game” or the “X” (close) button or whatever. Just something to make clear it's the final screen
- On the very final screen in the entire game, re-label the button to “Roll credits” or something, so it's clear that after clicking this button, the game literally ends

**Comment by dorkster** [comment]
* There's no way to pause on a scene for an infinite amount of time. Though, flare-game's scene pauses are 8 seconds, which is quite short. For now, we could increase these to something like 1 minute per scene.
* I agree, a back button would be useful. We'll have to change how our scenes are processed to allow random access. Currently, it's a queue where the last scene gets popped off the queue when moving to a new scene.
* Again, I agree that a proper "The End" would be nice.
* We *do* change the arrow to close button when on the last scene. The problem with the end scene is that the credits cutscene is tacked on to the end of the normal ending cutscene, making it all one big "cutscene". The close button is as such show when the credits are rolling.

**Comment by basxto** [comment]
I have seen games offering galleries, where you can rewatch already seen / unlocked cut scenes.

This would help slow readers or when you haven’t played the game for a while.

**Comment by Wuzzy2** [comment]
> There's no way to pause on a scene for an infinite amount of time.

Wait, whaaaaat? This is absurd.

Other stuff makes sense, more or less.

> I have seen games offering galleries, where you can rewatch already seen / unlocked cut scenes.

New issue.

**Comment by dorkster** [comment]
>Wait, whaaaaat? This is absurd.

In the context of GameStateCutscene's past available functionality, it makes more sense. There was no visible button to advance scenes (although pressing Enter/Space would advance), so it wasn't clear when there was more than one scene in a cutscene. Thus, it made more sense to force auto-advancing scenes. Of course, that's no longer an issue, so I think we could treat `pause=-1` as an infinite pause time for a scene.

As for having a cutscene "gallery", I think this could be done on the game side. We could add an event/NPC that would let the player re-watch unlocked cutscenes from a hub area.

**Comment by Nikolice** [comment]
Who – is the developer of „GameStateCutscene“ engine?‥ Is it – you?‥
If not, – they – **de-serve** to get this issue re-port, too: as not only we – are (possibly) facing the problem… I mean: that – would improve not only a „Flare“ game.

**Comment by dorkster** [comment]
Sorry I took so long to get to this. With e8d67a25a6a844d774d225ad63921881c539e1f5 and https://github.com/clintbellanger/flare-game/commit/58c37f36787c58deb764eb32254a72bc8922c499, you can now move back/forth through cutscenes at your leisure.

(Almost forgot: I also add a "The End" to the ending cutscene: https://github.com/clintbellanger/flare-game/commit/84b037fb21499ebf8792fc6512750fcb078abd3e)
