### ISSUE TITLE
Loot statistics are off by one

### ISSUE THREAD

**Issue by x42** [clintbellanger/flare-engine#1671]
https://github.com/clintbellanger/flare-engine/blob/b1835d5d094c6860e5d7c2fd32310208b2d5a58a/src/LootManager.cpp#L258

this should be
```
int chance = 1 + rand() % 100; 
```
To produce a range  1..100  to match the  "greater than or equal to" comparison at

https://github.com/clintbellanger/flare-engine/blob/b1835d5d094c6860e5d7c2fd32310208b2d5a58a/src/LootManager.cpp#L321

Also using a range 1..100 is more practical here, compared to changing the semantics to match 0..99

* `loot=<id>,0`  is special cased:  always drop unconditionally.
* `loot=<id>,1`  should have a 1% chance
...
* `loot=<id>,100`  should drop unless there is a better alternative

PS. Due to this bug, all 1%-drop unique items in campaigns had a 2% chance. Perhaps their loot probability should be increased.

**Comment by dorkster** [comment]
Ah, thanks for catching this. We have a function called `Math::randBetween()` that can be used appropriately here. Fix on the way.

And as for unique items in flare-game, they're supposed to have a 1% drop rate, so I'll leave them as-is.
