### ISSUE TITLE
Review of Enemy Powers

### ISSUE THREAD

**Issue by RyanDansie** [clintbellanger/flare-engine#710]
I would like to alter the way that the 4 main enemy powers are defined. So instead of having the 4 powers like power_melee_phys etc, just have multiple power=x or possibly power1=x. There would not necessarily be a limit to the number of powers which an enemy could have available. I dont expect that the limit would be an issue but the naming would be cleaner.

If it were to be done in this way, there would need to be a way to differentiate between ranged and melee powers. This could be done with a flag e.g. power=x,true or it could be a different attribute e.g. power_ranged=x. Another possibility is specifying the actual range for each power e.g. power=x,5.

Another consideration is that within the current code, once an enemy enters melee range, they no longer use their ranged powers. It could be kept like this or the enemy could be able to use any of the available powers which are within range. This could also be specified for each power e.g. a power can be both a melee and a ranged power.

Another aspect of enemy powers is the % chance to use a power. The % chance behaviour is not necessarily as a modder might expect e.g. if you specify 2 powers with 50% chance each, it doesnt have an equal chance to cast each power because the % chance is evaluated in a specific order. So the actual % chance turns out to be power1=50% and power2=25%. Im not sure whether there would be a better way to evaluate % chances but im just including it here for consideration and discussion.

Finally i want to add a new aspect to enemy powers which is a minimum level requirement. It would be implemented so that it doesnt need to be specified if there should be no level requirement. The purpose of this is to allow the same enemy to have additional powers at higher levels.

Please share any thoughts and insights on this.

**Comment by dorkster** [comment]
I feel this is worth tackling before 1.0. I want to have something like the following syntax for defining enemy powers:

```
power=type,id,chance
```

Examples:

```
power=melee,1,10
power=beacon,130,100
power=on_death,50,5
etc...
```

Rolling power chances would work like loot drops do right now. When we want to roll for a power of a certain type, we will:

- do our initial roll
- find powers that match the type we want AND have a chance >= to our roll
- randomly pick on of the powers from this subset

**Comment by dorkster** [comment]
I've finished my implementation: https://github.com/dorkster/flare-engine/commit/7fe4723b750cd10c7045303513da7b57745c15d8

I'm very happy with how this simplifies the powers sections of enemy definitions. I've converted the empyrean_campaign enemies to the new data spec so far. After I convert the alpha_demo enemies, I'll push all of this upstream.

**Comment by clintbellanger** [comment]
This design is a major improvement, well done!
