### ISSUE TITLE
[INFO] Packaging directories, mods.txt, and mods/default

### ISSUE THREAD

**Issue by makrohn** [clintbellanger/flare-engine#725]
https://github.com/makrohn/polymorphable/issues/45

I'd just like to point people towards this issue in the Polymorphable repository, where we have some real-world packaging going on for a Total Conversion game.  I think it's pretty well figured out by now, but should be a valuable place to look for input on how to handle filepaths, mods, etc.

**Comment by dorkster** [comment]
Closing this in an effort to clean up our issues list.

If any specific questions regarding mod structure come up, I will answer them and provide docs in the wiki.
