### ISSUE TITLE
Add missile reflection

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#78]
Migrated from clintbellanger/flare#43

Allow the creation of missile powers that reflect when hitting a wall, instead of dissipating. Look for a good spot (maybe the MapCollision class?) to calculate reflection angle.

For fun, try adding a Block-based power that reflects enemy missiles back at the enemy. This could be a very fun power for melee builds vs. pesky ranged creatures.

**Comment by dorkster** [comment]
Entities can now reflect missile powers, so half of this is done.

**Comment by dorkster** [comment]
Wall reflection was added a while ago [here](https://github.com/clintbellanger/flare-engine/commit/f8f6ae65bf001b74421179f2e678e75a59681549), so this is finished.
