### ISSUE TITLE
Split flarerpg.org into engine and game sites

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#864]
Flare, the stand-alone engine, needs its own website.
- It needs neutral art (not the same art that flare-game uses)
- It needs to focus on engine news, not on my personal work

Right now I'm leaning towards giving flare-game its own branding (new name), keeping the engine on a newly-designed flarerpg.org, and have an entirely new domain for flare-game.

We can expect Flare to jump in popularity when it hits a stable engine 1.0. So before that additional wave of attention comes, I'd like Flare to only mean the Engine.

Any thoughts on this? If there's general agreement then I'll move on with this plan.

**Comment by dorkster** [comment]
Done!
