### ISSUE TITLE
Please consider using Coverity Scan (free for open source)

### ISSUE THREAD

**Issue by tomreyn** [clintbellanger/flare-engine#932]
I'm a contributor to MegaGlest (an open source RTS game), which recently started using Coverity Scan for static source code analysis. 
https://en.wikipedia.org/wiki/Static_code_analysis

While we surely would prefer to only rely on cppcheck (which is already pretty useful!), clang/llvm's source code analysis and similar open source tools to produce open source software, Coverity Scan has helped us find a notable amount of flaws which the other tools did not, at a very low false positive rate. While this may sound like spam, I have no ties to Coverity other than agreeing to their TOS (which do not require me to advertise their product), nor NSA (other than everyone else has, I hope).

https://scan.coverity.com/about

Since you are approaching a v1.0 release, it might be nice to run it once or twice before you release and fix some of the bugs it would most likely find (I'm not trying to insult you here), as it did for many other projects including several popular open source games such as Wesnoth and 0 A.D., but also many fundamental open source software projects in general:
https://scan.coverity.com/projects

The sign-up process as well as the scan workflow are discussed at:
https://communities.coverity.com/videos/1114

Several questions, including which projects may be scanned on this platform and how often you may submit a new build for review are discussed here:
https://scan.coverity.com/faq

To sign up (you may do so using your Github account), start here:
https://scan.coverity.com/

**Comment by dorkster** [comment]
The latest master put us at 3 outstanding defects. All of which I determined to be false positives/intentional.
