### ISSUE TITLE
Flare 2.0 transition logistics

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#940]
The current state of the main Flare-Engine branch is pretty close to what we want for Flare 1.0. The engine won't change drastically from 1.0 to 1.1 or 1.2 (mostly just expanding the options for existing features instead of adding completely new ones). People can work on large games knowing the engine spec won't change underneath them.

You guys have SDL2 just about ready to go in that experimental branch. We want to support Flare on devices that won't have SDL2. So soon this SDL2 implementation of Flare will be the starting point for Flare 2.0. While Flare 1.x will be maintained for stability for many games to use now, Flare 2.x will be used to add more features like realtime lighting and random content generation.

Basically Flare splits into two projects:
- Flare 1.x (stable)
- Flare 2.x (experimental)

How do we make this transition? I've never been part of a project (much less leading one) that went through a big fork like this. So I'm looking for discussion and ideas.

I plan on being the maintainer of the Flare Engine 1.x version, which will continue to be in this repo. I don't think I have the time or energy to oversee the Flare 2.x work -- I can be a contributing member, but someone(s) else have to take the lead on Flare 2. (Any suggestions/nominations/volunteers?).

Should Flare 2 get a new github repo? Seems like it would be less messy that way.

Should Flare 1 and 2 share other resources? I think so. E.g. the Flare website and Sourceforge accounts can have both (and I'll share access to those).

How do we version number Flare 2? Imagine this SDL2 branch becomes the first alpha version of Flare 2. Do we call that Flare 2.01?

Is it time now to create a Flare 2 repo? Under whose github account?

What other obvious decisions am I forgetting?

**Comment by shipso** [comment]
bonjour , c'est pour le jeux  ''flare''    alors voila pour le jeux faudrait mettre plus de quéte , et aussi pourquoi ne pas faire une option pour fabriquer des objet et des arme par exemple : crée des métier comme dans ''world of war craft''  (heboriste . forgeron ext...) , et aussi mettre en place un systéme d'échange d'objet , et une arene de combat multijoueur ,

**Comment by Bertram25** [comment]
> bonjour , c'est pour le jeux ''flare'' alors voila pour le jeux faudrait mettre plus de quéte , et aussi pourquoi ne pas faire une option pour fabriquer des objet et des arme par exemple : crée des métier comme dans ''world of war craft'' (heboriste . forgeron ext...) , et aussi mettre en place un systéme d'échange d'objet , et une arene de combat multijoueur , 

Just translating:
Hello, it is for the "flare" game. Well, the game would use more quests, and also why not add an option to make new items and weapons for instance : Create jobs like in "World of Warcraft" (herbalist, smith, ect ...), and also add an item trade system, and a multiplayer fighting arena.
