### ISSUE TITLE
Complete the RenderDevice abstraction

### ISSUE THREAD

**Issue by hean01** [clintbellanger/flare-engine#969]
I just looked into the RenderDevice abstraction and it have a lot of issues that prevents using it for anything else than SDL. 

For a abstraction to work ownership of resources must be taken care of, whatever backend instantiates, is owned and freed by backend. So the RenderDevice must be seen as a factory of Image instances. The backend needs to keep track of resources it uses and its not up to anything else to create / destroy them. This should be true for Image, Sprite and Renderable. 
 
----
Identified problems:

__class RenderDevice__
 * Includes interface for drawing operation onto an Image, this should be moved into Image class for clarification. There are drawing operations to a RenderingDevice which draws onto screen and should not be mixed with drawing into an Image.

 * TTF_Font is used for drawText() this should be abstracted into class IFont and a SDLFont using SDL TTF implementation should be used.

 *  There are internal helper functions that are public which should be private. drawLine(Image...) for example, this would be solved when its moved into class Image.

 * There is a ImageManager that uses RenderDevice to load images however its only used in one place (animations). Move the current ImageManager class that manages loading and shared use of images into RenderingDevice and use reference counting on Image instances.
 *Fixed in commit 0a31ac3*

__class Image__
 * Includes implementation for using a SDL_Surface, this class should be made abstract and a class SDLImage should implement SDL specific parts.
 *Fixed in commit 60e51aa*

 * An image is instantiated by RenderDevice and assigned to several objects. We should therefor see the RenderDevice as a factory for Image instances. The use of Image is shared among other instances and shall therefor implement a reference counting for proper management of the resource. Last unref() can safely discard the resource.
 *Fixed in commit  17163a0*

__class ISprite__
 * Uses abstract memeber function on functions that should behave the same whatever implementation. Move implementation from SDLRenderDevice of Sprite into ISprite so it could be shared. No point of making them virtual at all, implementation belongs to Sprite.
 *Fixed in commit  17163a0*

 * Rename ISprite to Sprite, the current Sprite implementation in SDLRenderDevice could probably be dropped. 
 *Fixed in commit  17163a0*

 * Should be instantiated from an Image, something like Image::createSprite(), this should increment a refrence on Image object. While destroying Sprite instance unrefs the Image.
 *Fixed in commit  17163a0*

__general__
 * The terminology needs to be sorted out, we have classes Image, Sprite and Renderable where Image is member variable of Sprite and Renderable, named sprite. This variable is public and accessed like r.sprite which is a high level of obfuscating the code.

* There are a few functions that uses Surface in their names, this is leftovers from SDL implementation where the functions returned a SDL_Surface. Now when those functions returns an Image the function names should be renamed. For example: Image createSurface() to Image createImage()

* The methods passes copies instead of references for example Sprite::setGraphics(Image s);
 *Fixed in commit  17163a0*

* Shared game data icons should not be initialized in a RenderDevice::loadIcons() implementation such as SDLRenderDevice. It belongs to the engine and needs to be moved to a proper place. 
*Fixed in commit  0e5c01d*

----

Enhancements:

__class RenderDevice__
 * Add createRenderable() createSprite() to Image for Renderable and Sprite factory.
 *Sprite fixed in commit 17163a0*

 * Use reference counters to control freeing of resources created by Factories
 *Image ref counting fixed in commit 0e5c01d*

**Comment by igorko** [comment]
@hean01 you can check out last changes that added abstraction for soundmanager, font and input engines. Is there anything we can do more? Just want to close this issue if everything planned is done.

**Comment by igorko** [comment]
@dorkster Looks like our sound system is still interwoven with engine itself (even while initially it was written as separate class and I have moved some definitions to base header). We have SDL_mixer calls all over the code:
![dependencies](https://cloud.githubusercontent.com/assets/1015344/7492783/2f5e1272-f404-11e4-9a5a-d1b127b7f011.jpg)
Currently for testing I need to fully remove SDL_mixer dependency, and it's not so easy as e.g with  FontEngine. Can you look into it and refactor in such way, so all SDL_mixer calls are isolated inside SDLSoundManager class?

**Comment by dorkster** [comment]
@igorko I'll take care of refactoring the SDL_mixer code.

**Comment by dorkster** [comment]
Okay, all the SDL_mixer bits are in SDLSoundManager now. I've also renamed RenderDeviceList to DeviceList since its usage has broadened.
