### ISSUE TITLE
Map Backdrops

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#973]
Migrated from https://github.com/clintbellanger/flare/issues/793

Originally opened by @clintbellanger 

Currently all map backdrops are black. Instead we want the option of a repeating image.

Further, we want the option to make this image scroll at a slower pace than the tile layers, to give a parallax feel.

As an example: perhaps we can find a repeating 512x512px starfield (public domain via NASA) image to use as the background for the new Warp Zone map.

The background_image and background_scroll options would be set in map files. Perhaps we also add background_color in case a map wants a different solid color background than black.

Scroll speed should probably be a percentage of the tile layers' speed. Perhaps integer based, default 100. When my brain is working better I'll help figure out this algorithm. I suppose it's something like map_to_screen's results multiplied by the scroll speed.

The background will repeat, so there needs to be an algorithm that tiles the image over the entire window size.

**Comment by dorkster** [comment]
This is implemented now, and supports several layers that move at different speeds relative to the camera. This gives a nice parallax effect.

Here's a before/after video of the Hyperspace map with a NASA star image + some GIMP difference clouds: https://youtu.be/_F-itFTBPVw

Our dungeon tileset makes some assumptions about the background always being black, so the tall brick tiles that descend into pits have transparency that shows the backgrounds underneath. Interestingly enough, the clouds in my above example have the illusion of appearing *above* the map tiles because of that transparency.

**Comment by clintbellanger** [comment]
Fantastic! I'm glad this works so well with just image= and speed= for each layer.

Those pit tiles are translucent for this exact reason, to give a misty effect from a background. I didn't know whether it would work well until now! I have similar tricks I want to try in future tile sets to give the impression of the background being reflected water.

**Comment by pennomi** [comment]
This had even more of an effect than I thought it would. Amazing job!

**Comment by dorkster** [comment]
Added a few new features:

* layers can move at fixed speeds regardless of camera movement
* layers can be rendered above specific tile layers

Here's a look at some weather effects I was able to create with these: https://youtu.be/bibcONDwXm0

**Comment by clintbellanger** [comment]
Ooh this is great! Going from "background" to straight up "parallax" is a good leap.

If performance isn't a limit, one thing to try to improve that rain and snow effect is to have about 3 similar layers (same graphic probably) with very slightly offsetting speed/direction

**Comment by dorkster** [comment]
Interesting idea about layering the weather effects.

As for performance, I'll need to do some profiling. If it's too bad, I'm considering adding an option to the video config to disable these layers all together. They are just eye candy after all.

**Comment by clintbellanger** [comment]
Simple moving backgrounds allow so much. A level where you're fighting on top of train cars, and the background is the track and cliffs moving by. Or fighting on a space ship with a starfield flying by in the background.

**Comment by clintbellanger** [comment]
Also something simpler that would be useful: an infinite plane of grass and weeds for outdoor levels that want to avoid the black off-map look. I think this could be made in Tiled easy enough and exported as a big image then made seamless.

**Comment by igorko** [comment]
I suppose "weather implementation" is not needed anymore after these changes. As I understand to one map you can add both weather(rain) and fill up black background around the map? Can you guys do this for some maps in alpha_demo/empyrean_campaign. It would be good feature presentation.

**Comment by igorko** [comment]
Also, can you do night/day change in this way? This will require new counter class (there was some done in branch some time ago). but anyway visual part is finished. Nice work!
